import { z } from "zod";
import { COMPLETION_FLOW_CONTRACT_V1 } from "./types";

const safeId = z.string().min(3).max(180).regex(/^[a-zA-Z0-9][a-zA-Z0-9._:-]*$/);
const digest = z.string().regex(/^sha256:[a-f0-9]{64}$/);
const time = z.string().datetime({ offset: true });
const sortedIds = z.array(safeId).min(1).max(100).superRefine((values, context) => {
  if (new Set(values).size !== values.length || values.some((value, index) => index > 0 && values[index - 1] >= value)) {
    context.addIssue({ code: "custom", message: "IDs must be sorted and unique" });
  }
});

export const effectFreeExecutionObservationSchemaV1 = z.object({
  contractVersion: z.literal(COMPLETION_FLOW_CONTRACT_V1),
  phase: z.enum(["initial", "revision"]),
  executionId: safeId,
  tenantId: safeId,
  projectId: safeId,
  jobId: safeId,
  attemptId: safeId,
  localPolicyRequestId: safeId,
  localPolicyRequestDigest: digest,
  operationDigest: digest,
  authorityDigest: digest,
  artifactId: safeId,
  artifactContentHash: digest,
  artifactManifestDigest: digest,
  producerClaimDigest: digest,
  artifactLineageDigest: digest,
  secretReceiptDigest: digest.optional(),
  completedAt: time,
  executionKind: z.literal("synthetic"),
  externalEffect: z.literal(false),
  networkUsed: z.literal(false),
  nativeProcessUsed: z.literal(false),
  liveProviderUsed: z.literal(false),
  approvalDecisionConsumed: z.literal(false),
  nodeApprovalAttestationPresent: z.literal(false),
  grantsApproval: z.literal(false),
  grantsExecutionAuthority: z.literal(false),
  observationDigest: digest,
}).strict();

export const completionFlowReceiptSchemaV1 = z.object({
  contractVersion: z.literal(COMPLETION_FLOW_CONTRACT_V1),
  workflowId: safeId,
  tenantId: safeId,
  projectId: safeId,
  questionAttentionId: safeId,
  questionAttentionDigest: digest,
  resolvedAttentionDigest: digest,
  messagePlanId: safeId,
  messagePlanDigest: digest,
  presentationId: safeId,
  presentationDigest: digest,
  callbackId: safeId,
  callbackRecordDigest: digest,
  responseProposalId: safeId,
  responseProposalDigest: digest,
  selectedOptionDigest: digest,
  preferenceId: safeId,
  preferenceDigest: digest,
  approvalRequestId: safeId,
  approvalRequestDigest: digest,
  approvalDecisionId: safeId,
  approvalDecisionDigest: digest,
  approvedOperationDigest: digest,
  approvedOperationDisposition: z.literal("approved_not_executed"),
  credentialCatalogEntryDigest: digest,
  secretGrantDigest: digest,
  secretReceiptDigest: digest,
  initialExecutionObservationDigest: digest,
  revisionExecutionObservationDigest: digest,
  acceptanceProfileId: safeId,
  acceptanceProfileDigest: digest,
  initialTargetId: safeId,
  initialTargetDigest: digest,
  initialReviewId: safeId,
  initialReviewDigest: digest,
  initialFindingIds: sortedIds,
  revisionId: safeId,
  revisionDigest: digest,
  revisedTargetId: safeId,
  revisedTargetDigest: digest,
  revisedVerificationIds: sortedIds,
  finalReviewId: safeId,
  finalReviewDigest: digest,
  finalSnapshotDigest: digest,
  finalStatus: z.literal("ready"),
  completedAt: time,
  liveEffectsPerformed: z.literal(false),
  approvedOperationExecuted: z.literal(false),
  productionCredentialMaterialPersisted: z.literal(false),
  nodeApprovalAttestationPresent: z.literal(false),
  grantsApproval: z.literal(false),
  grantsExecutionAuthority: z.literal(false),
  receiptDigest: digest,
}).strict();
