"use client";
import { useEffect,useState } from "react";
import type { IdeaLabSessionProjectionV1 } from "@/src/idea-lab/v1";

function command(){return{commandId:`command.idea:${crypto.randomUUID()}`,requestedAt:new Date().toISOString()};}
function projectId(title:string){const slug=title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)||"new-idea";return`project:${slug}`;}
function stateLabel(value:string){return value.replaceAll("_"," ");}
export function IdeaLabOperatorControls({enabled=false,initialSessions=[]}:{enabled?:boolean;initialSessions?:IdeaLabSessionProjectionV1[]}){
  const[title,setTitle]=useState(""),[summary,setSummary]=useState(""),[customer,setCustomer]=useState(""),[sessionId,setSessionId]=useState<string>(),
    [sessions,setSessions]=useState(initialSessions),[status,setStatus]=useState(enabled?"Ready for protected idea intake.":"Protected runtime not configured. Controls are safely disabled."),[busy,setBusy]=useState(false);
  function select(session:IdeaLabSessionProjectionV1){setSessionId(session.sessionId);setTitle(session.title);setSummary(session.ideaSummary);setCustomer(session.targetCustomer);setStatus(`Resumed ${session.title}: ${stateLabel(session.state)}.`);}
  useEffect(()=>{if(!enabled)return;let ignore=false;void fetch("/api/v1/idea-lab/sessions",{headers:{accept:"application/json"}}).then(async response=>{const payload=await response.json() as{error?:string;sessions?:IdeaLabSessionProjectionV1[]};if(!response.ok)throw new Error(payload.error??"session_catalog_unavailable");return payload.sessions??[];}).then(loaded=>{if(ignore)return;setSessions(loaded);const first=loaded[0];if(first){setSessionId(first.sessionId);setTitle(first.title);setSummary(first.ideaSummary);setCustomer(first.targetCustomer);setStatus(`Resumed ${first.title}: ${stateLabel(first.state)}.`);}}).catch(error=>{if(!ignore)setStatus(error instanceof Error?error.message:"session_catalog_unavailable");});return()=>{ignore=true;};},[enabled]);
  async function send(path:string,body:unknown){setBusy(true);try{const response=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),payload=await response.json() as{error?:string;session?:IdeaLabSessionProjectionV1;project?:{projectId:string}};if(!response.ok)throw new Error(payload.error??"request_failed");if(payload.session){setSessionId(payload.session.sessionId);setSessions(current=>[payload.session!,...current.filter(item=>item.sessionId!==payload.session!.sessionId)]);setStatus(`Session ${stateLabel(payload.session.state)}.`);}else if(payload.project)setStatus(`Project ${payload.project.projectId} created.`);else setStatus("Owner decision recorded.");}catch(error){setStatus(error instanceof Error?error.message:"request_failed");}finally{setBusy(false);}}
  const unavailable=!enabled||busy;
  return <section className="idea-lab-operator" aria-labelledby="idea-lab-operator-title"><div><p className="eyebrow">Protected owner workflow</p><h2 id="idea-lab-operator-title">Start or resume a business-idea panel</h2><p>Control Room selects the distinct panel identities. Creating the session, running the panel, synthesizing advice, and making the owner decision are separate recorded steps.</p><div className="idea-lab-session-catalog" aria-label="Protected idea sessions"><h3>Recent sessions</h3>{sessions.length?<ul>{sessions.map(session=><li key={session.sessionId}><button type="button" disabled={!enabled||busy} onClick={()=>select(session)}><strong>{session.title}</strong><span>{stateLabel(session.state)}</span></button></li>)}</ul>:<p>No protected sessions loaded.</p>}</div></div>
    <form onSubmit={event=>{event.preventDefault();void send("/api/v1/idea-lab/sessions",{...command(),title,ideaSummary:summary,targetCustomer:customer,maxRounds:1,maxDurationSeconds:300,maxCostUsd:2});}}>
      <label>Idea title<input value={title} onChange={event=>setTitle(event.target.value)} disabled={!enabled} required maxLength={120}/></label>
      <label>What is the idea?<textarea value={summary} onChange={event=>setSummary(event.target.value)} disabled={!enabled} required maxLength={800}/></label>
      <label>Who is it for?<input value={customer} onChange={event=>setCustomer(event.target.value)} disabled={!enabled} required maxLength={300}/></label>
      <div className="idea-lab-command-row"><button type="submit" disabled={unavailable}>Create session</button><button type="button" disabled={unavailable||!sessionId} onClick={()=>void send(`/api/v1/idea-lab/sessions/${encodeURIComponent(sessionId!)}/start`,command())}>Run bounded panel</button><button type="button" disabled={unavailable||!sessionId} onClick={()=>void send(`/api/v1/idea-lab/sessions/${encodeURIComponent(sessionId!)}/synthesis`,command())}>Synthesize</button><button type="button" disabled={unavailable||!sessionId} onClick={()=>void send(`/api/v1/idea-lab/sessions/${encodeURIComponent(sessionId!)}/cancel`,command())}>Cancel</button></div>
      <div className="idea-lab-command-row"><button type="button" disabled={unavailable||!sessionId} onClick={()=>void send(`/api/v1/idea-lab/sessions/${encodeURIComponent(sessionId!)}/decision`,{decision:"save",safeReasonCode:"owner_saved_for_later"})}>Save idea</button><button type="button" disabled={unavailable||!sessionId} onClick={()=>void send(`/api/v1/idea-lab/sessions/${encodeURIComponent(sessionId!)}/decision`,{decision:"create_project",safeReasonCode:"owner_promoted_for_validation",project:{projectId:projectId(title),workspaceName:title,title:`Validate ${title}`,summary,projectKind:"business_validation",priority:60}})}>Create monitored project</button></div>
      <p role="status">{status}</p>
    </form>
  </section>;
}
