"use client";
import { useEffect,useState } from "react";
import type { ProjectWorkspaceSnapshotV1 } from "@/src/project-workspace/v1/types";
import type { ProjectRegistryProjectionV1 } from "@/src/idea-lab/v1/types";
import { ProjectWorkspaceShell } from "./project-workspace-shell";
import { ProtectedProjectWorkspaceRead } from "./protected-project-workspace-read";
import { IdeaProjectLifecycleControls } from "./idea-project-lifecycle-controls";
function label(value:string){return value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());}
export function IdeaProtectedProjectWorkspace({projectId,sectionId="overview"}:{projectId:string;sectionId?:string}){const[project,setProject]=useState<ProjectRegistryProjectionV1>(),[workspace,setWorkspace]=useState<ProjectWorkspaceSnapshotV1>(),[error,setError]=useState<string>();
  useEffect(()=>{let current=true;void fetch(`/api/v1/idea-lab/projects/${encodeURIComponent(projectId)}`,{headers:{accept:"application/json"}}).then(async response=>{const payload=await response.json()as{project?:ProjectRegistryProjectionV1;workspace?:ProjectWorkspaceSnapshotV1;error?:string};if(!response.ok||!payload.project||!payload.workspace||payload.project.projectId!==projectId||payload.workspace.projectId!==projectId)throw new Error(payload.error??"project_not_found");if(current){setProject(payload.project);setWorkspace(payload.workspace);}}).catch(reason=>{if(current)setError(reason instanceof Error?reason.message:"project_read_unavailable");});return()=>{current=false;};},[projectId]);
  if(error)return <main className="detail-main"><a className="detail-back" href="/ideas">← Back to Idea Lab</a><section className="detail-card"><h1>Protected project unavailable</h1><p>{label(error)}</p><small>No fixture was substituted for protected project truth.</small></section></main>;
  if(!project||!workspace)return <main className="detail-main"><p className="operator-data-status loading" role="status">Loading protected local project…</p></main>;
  let content=<section className="detail-card"><h2>{label(sectionId)}</h2><p>No protected records exist in this section yet.</p><small>No fixture or unrelated project data is substituted.</small></section>;
  if(sectionId==="overview")content=<div className="detail-grid"><section className="detail-card"><h2>Project lifecycle</h2><div className="capability-list"><article><h3>Current state</h3><p>{label(project.lifecycleState)}</p><small>Lifecycle version {project.version}</small></article><article><h3>Origin</h3><p>Owner-promoted Idea Lab session</p><small>{project.sourceIdeaSessionId}</small></article></div></section><section className="detail-card"><h2>Project purpose</h2><p>{project.summary}</p><small>Priority {project.priority} · repository-fake pilot</small></section></div>;
  if(sectionId==="settings")content=<div className="detail-grid"><section className="detail-card"><h2>Identity</h2><p>{project.projectId}</p><small>{project.projectKind} · {project.workspaceName}</small></section><section className="detail-card"><h2>Lifecycle controls</h2><IdeaProjectLifecycleControls project={project} enabled/></section></div>;
  if(sectionId==="idea-origin")content=<section className="detail-card"><h2>Idea origin</h2><p>{project.summary}</p><small>Source session {project.sourceIdeaSessionId} · decision {project.sourceDecisionDigest}</small></section>;
  return <ProjectWorkspaceShell snapshot={workspace} workspaceName={project.workspaceName} health="healthy" currentSectionId={sectionId} protectedOnly><ProtectedProjectWorkspaceRead projectId={project.projectId} sectionId={sectionId}/>{content}</ProjectWorkspaceShell>;}
