"use client";
import { useEffect,useState,type FormEvent } from "react";
export function LocalPilotOwnerSession(){const[code,setCode]=useState(""),[active,setActive]=useState(false),[busy,setBusy]=useState(true),[status,setStatus]=useState("Checking the local owner session.");
  useEffect(()=>{let current=true;void fetch("/api/v1/local-pilot/session",{headers:{accept:"application/json"}}).then(async response=>{const payload=await response.json()as{authenticated?:boolean;expiresAt?:string};if(!current)return;
    setActive(response.ok&&payload.authenticated===true);setStatus(response.ok?`Owner session active until ${new Date(payload.expiresAt!).toLocaleTimeString()}.`:"Enter the one-time code printed by the owner-attended launcher.");}).catch(()=>{if(current)setStatus("Local owner-session check is unavailable.");}).finally(()=>{if(current)setBusy(false);});return()=>{current=false;};},[]);
  async function signIn(event:FormEvent){event.preventDefault();setBusy(true);try{const response=await fetch("/api/v1/local-pilot/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ownerCode:code})}),payload=await response.json()as{error?:string;expiresAt?:string};
    if(!response.ok)throw new Error(payload.error??"local_pilot_unavailable");setCode("");setActive(true);setStatus(`Owner session active until ${new Date(payload.expiresAt!).toLocaleTimeString()}. Reloading protected controls…`);window.location.reload();}
    catch(error){setStatus(error instanceof Error?error.message:"local_pilot_unavailable");}finally{setBusy(false);}}
  return <section className="local-pilot-session" aria-labelledby="local-pilot-session-title"><div><p className="eyebrow">Local repository-fake pilot</p><h2 id="local-pilot-session-title">Owner session</h2><p>No provider, production database, or public network is connected.</p></div>{active?<p className="local-pilot-session-active" role="status">{status}</p>:<form onSubmit={signIn}><label>One-time owner code<input type="password" autoComplete="one-time-code" value={code} onChange={event=>setCode(event.target.value)} minLength={24} maxLength={200} disabled={busy} required/></label><button type="submit" disabled={busy||code.length<24}>Start 15-minute session</button><p role="status">{status}</p></form>}</section>;}
