import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";
import { COMPLETION_GATE_SCHEMA_VERSION_V1, consequentialApprovalDecisionSchemaV1, type ConsequentialApprovalDecisionV1 } from "../src/completion-gate/v1/index.ts";
import {
  ABS_NEWS_PROJECT_ID_V1, ABS_NEWS_WORKSPACE_ID_V1, AbsNewsInjectedLiveReadTransportV1, AbsNewsLiveReadSimulationCoordinatorV1,
  SqliteAbsNewsLiveReadStoreV1, buildAbsNewsLiveReadApprovalRequestV1, buildAbsNewsLiveReadAuthorizationV1,
  buildAbsNewsLiveReadRequestV1, buildAbsNewsLiveReadTransportResultV1, parseAbsNewsLiveReadRequestV1,
  type AbsNewsLiveReadRequestV1, type AbsNewsLiveReadSourceV1, type AbsNewsLiveReadTransportV1,
} from "../src/project-adapters/abs-news/v1/index.ts";
import { ProjectWorkspaceContractErrorV1 } from "../src/project-workspace/v1/index.ts";
import { sha256Digest } from "../src/security/index.ts";
import type { HostResultCollectorV1 } from "../src/security/host-value.ts";
import { observedProxy } from "./proxy-test-helper.ts";

const scope={tenantId:"tenant.owner",workspaceId:ABS_NEWS_WORKSPACE_ID_V1,projectId:ABS_NEWS_PROJECT_ID_V1};
const t0="2026-08-30T00:00:00.000Z",t1="2026-08-30T00:01:00.000Z",t2="2026-08-30T00:02:00.000Z",t3="2026-08-30T00:02:01.000Z",t4="2026-08-30T00:02:02.000Z",t10="2026-08-30T00:10:00.000Z";
const key=new Uint8Array(32).fill(59);

function request(overrides:Record<string,unknown>={}):AbsNewsLiveReadRequestV1{return buildAbsNewsLiveReadRequestV1({requestId:"request:abs:live-rehearsal",...scope,jobId:"job:abs:collector",attemptId:"attempt:abs:collector:1",effectIntentId:"effect:abs:live-read",sources:[{sourceId:"source:abs:rss",sourceKind:"rss",sourceLabel:"Synthetic RSS",endpointUrl:"https://rss.example.com/ai.xml"},{sourceId:"source:abs:sitemap",sourceKind:"sitemap",sourceLabel:"Synthetic sitemap",endpointUrl:"https://site.example.com/sitemap.xml"}],maxItemsPerSource:5,maxResponseBytes:4096,maxTotalBytes:8192,maxRuntimeSeconds:10,allowedContentTypes:["application/rss+xml","application/xml"],requestedAt:t0,expiresAt:t10,...overrides});}
function decision(req:AbsNewsLiveReadRequestV1,mode:"simulation"|"owner_live"="simulation"):ConsequentialApprovalDecisionV1{const approval=buildAbsNewsLiveReadApprovalRequestV1(req);return consequentialApprovalDecisionSchemaV1.parse({schemaVersion:COMPLETION_GATE_SCHEMA_VERSION_V1,id:`approval-decision:abs:${mode}`,tenantId:req.tenantId,projectId:req.projectId,requestId:approval.id,requestDigest:sha256Digest(approval),operationDigest:req.operationDigest,policyDecisionId:mode==="simulation"?"policy:synthetic:abs-live-read":"policy:owner:abs-live-read",decision:"approved",decidedBy:{actorId:mode==="simulation"?"actor:synthetic-owner":"actor:owner",actorType:"human"},factor:"strong",authenticationEventDigest:sha256Digest({mode}),decidedAt:t1,expiresAt:t10,safeReasonCode:mode==="simulation"?"synthetic_contract_evidence":"owner_approved_exact_live_read",grantsExecutionAuthority:false,requiresSeparateNodeAttestation:true}) as ConsequentialApprovalDecisionV1;}
function bundle(mode:"simulation"|"owner_live"="simulation"){const req=request(),approvalRequest=buildAbsNewsLiveReadApprovalRequestV1(req),approvalDecision=decision(req,mode),authorization=buildAbsNewsLiveReadAuthorizationV1({request:req,approvalRequest,approvalDecision,authorizationMode:mode});return{request:req,approvalRequest,approvalDecision,authorization};}
function transportResult(source:AbsNewsLiveReadSourceV1,index:number,overrides:Record<string,unknown>={}){const batch={batchId:`batch:abs:live:${index}`,sourceId:source.sourceId,sourceKind:source.sourceKind,sourceLabel:source.sourceLabel,collectedAt:t3,items:[{collectionItemId:`item:abs:live:${index}`,sourceId:source.sourceId,sourceKind:source.sourceKind,sourceLabel:source.sourceLabel,title:`Synthetic release ${index}`,summary:"Sanitized injected evidence for the live-read rehearsal contract.",discoveredUrl:`https://article${index}.example.com/release`,observedAt:t3,directlyVerified:true,contentDigest:sha256Digest({index}),containsRawNewsletterBody:false,grantsNetworkAuthority:false}],synthetic:true,networkUsed:false,grantsNetworkAuthority:false};return buildAbsNewsLiveReadTransportResultV1({status:"succeeded",sourceId:source.sourceId,sourceDigest:source.sourceDigest,requestedUrl:source.endpointUrl,finalUrl:source.endpointUrl,responseStatus:200,contentType:source.sourceKind==="rss"?"application/rss+xml":"application/xml",responseByteCount:1000+index,responseBodyDigest:sha256Digest({body:index}),batch,observedAt:t3,synthetic:true,networkUsed:false,redirectsFollowed:0,cookiesSent:false,authorizationHeaderSent:false,credentialsResolved:false,rawBodyReturned:false,retainsRawBody:false,...overrides});}
async function location(){const directory=await mkdtemp(join(tmpdir(),"abs-live-read-"));return{directory,path:join(directory,"ledger.sqlite")};}

test("CR9D-ABS-060 freezes a public unauthenticated zero-cost request and keeps simulation separate from owner-live authority",()=>{const req=request();assert.deepEqual({sources:req.maxSources,cost:req.maxCostUsd,credentials:req.credentialReferenceDigests,redirects:req.allowsRedirects,cookies:req.allowsCookies,auth:req.allowsAuthentication,provider:req.allowsProviderCalls,raw:req.retainsRawBody,authorized:req.liveReadAuthorized},{sources:2,cost:0,credentials:[],redirects:false,cookies:false,auth:false,provider:false,raw:false,authorized:false});const simulation=bundle("simulation").authorization,owner=bundle("owner_live").authorization;assert.equal(simulation.networkReadAuthorized,false);assert.equal(owner.networkReadAuthorized,true);assert.equal(owner.grantsExecutionAuthority,false);assert.throws(()=>buildAbsNewsLiveReadAuthorizationV1({...bundle("simulation"),authorizationMode:"owner_live"}),(error:unknown)=>error instanceof ProjectWorkspaceContractErrorV1);for(const endpointUrl of ["https://rss.example.com/ai.xml?token=1","https://user:pass@rss.example.com/ai.xml","https://localhost/ai.xml","http://rss.example.com/ai.xml"])assert.throws(()=>request({sources:[{sourceId:"source:bad",sourceKind:"rss",sourceLabel:"Bad",endpointUrl}]}),ProjectWorkspaceContractErrorV1);});

test("CR9D-ABS-060 injected two-source rehearsal is bounded, durable, replay-safe, and retains no raw body",async()=>{const target=await location();try{let store=new SqliteAbsNewsLiveReadStoreV1(target.path,scope,{integrityKey:key,mode:"create"});const registered=store.register(bundle());assert.equal(registered.replayed,false);const transport=new AbsNewsInjectedLiveReadTransportV1(registered.bundle.request.sources.map((source,index)=>transportResult(source,index))),coordinator=new AbsNewsLiveReadSimulationCoordinatorV1(store,transport),first=await coordinator.run({requestId:registered.bundle.request.requestId,claimedAt:t2,markedAt:t3,settledAt:t4});assert.deepEqual({disposition:first.outcome.disposition,items:first.outcome.itemCount,bytes:first.outcome.totalResponseBytes,calls:transport.callCount,network:first.outcome.networkUsed,raw:first.outcome.retainsRawBody,work:first.outcome.createsWorkItem},{disposition:"succeeded",items:2,bytes:2001,calls:2,network:false,raw:false,work:false});const before=store.verifyIntegrity();store.close();store=new SqliteAbsNewsLiveReadStoreV1(target.path,scope,{integrityKey:key,mode:"open"});const replayTransport=new AbsNewsInjectedLiveReadTransportV1([]),replay=await new AbsNewsLiveReadSimulationCoordinatorV1(store,replayTransport).run({requestId:registered.bundle.request.requestId,claimedAt:t2,markedAt:t3,settledAt:t4});assert.equal(replay.replayed,true);assert.equal(replayTransport.callCount,0);assert.deepEqual(store.verifyIntegrity(),before);store.close();}finally{await rm(target.directory,{recursive:true,force:true});}});

test("CR9D-ABS-060 definite pre-response failure is terminal and does not call later sources",async()=>{const target=await location();try{const store=new SqliteAbsNewsLiveReadStoreV1(target.path,scope,{integrityKey:key,mode:"create"}),registered=store.register(bundle()),source=registered.bundle.request.sources[0]!,failure=buildAbsNewsLiveReadTransportResultV1({status:"definite_failure",sourceId:source.sourceId,sourceDigest:source.sourceDigest,requestedUrl:source.endpointUrl,finalUrl:source.endpointUrl,responseByteCount:0,safeFailureCode:"connection_refused_before_response",observedAt:t3,synthetic:true,networkUsed:false,redirectsFollowed:0,cookiesSent:false,authorizationHeaderSent:false,credentialsResolved:false,rawBodyReturned:false,retainsRawBody:false}),transport=new AbsNewsInjectedLiveReadTransportV1([failure]),outcome=(await new AbsNewsLiveReadSimulationCoordinatorV1(store,transport).run({requestId:registered.bundle.request.requestId,claimedAt:t2,markedAt:t3,settledAt:t4})).outcome;assert.equal(outcome.disposition,"definite_failure");assert.equal(transport.callCount,1);assert.equal((await new AbsNewsLiveReadSimulationCoordinatorV1(store,new AbsNewsInjectedLiveReadTransportV1([])).run({requestId:registered.bundle.request.requestId,claimedAt:t2,markedAt:t3,settledAt:t4})).replayed,true);store.close();}finally{await rm(target.directory,{recursive:true,force:true});}});

test("CR9D-ABS-060 redirects, over-limit evidence, malformed handoff, and Proxy results become terminal ambiguity",async()=>{for(const variant of ["redirect","oversize","proxy"] as const){const target=await location();try{const store=new SqliteAbsNewsLiveReadStoreV1(target.path,scope,{integrityKey:key,mode:"create"}),registered=store.register(bundle());let traps=0;const transport:AbsNewsLiveReadTransportV1={async read(input:{request:AbsNewsLiveReadRequestV1;source:AbsNewsLiveReadSourceV1},collector:HostResultCollectorV1){const ordinary=variant==="redirect"?transportResult(input.source,0,{finalUrl:"https://other.example.com/feed.xml"}):transportResult(input.source,0,{responseByteCount:5000});if(variant==="proxy"){const proxied=observedProxy(ordinary,"transparent");traps=proxied.trapCount();assert.throws(()=>collector.submit(proxied.value));traps=proxied.trapCount();return;}collector.submit(ordinary);}};const outcome=(await new AbsNewsLiveReadSimulationCoordinatorV1(store,transport).run({requestId:registered.bundle.request.requestId,claimedAt:t2,markedAt:t3,settledAt:t4})).outcome;assert.equal(outcome.disposition,"ambiguous");assert.equal(outcome.safeReasonCode,"post_marker_outcome_unknown");assert.equal(traps,0);store.close();}finally{await rm(target.directory,{recursive:true,force:true});}}});

test("CR9D-ABS-060 restart after marker becomes terminal ambiguity and authenticated deletion is detected",async()=>{const target=await location();try{let store=new SqliteAbsNewsLiveReadStoreV1(target.path,scope,{integrityKey:key,mode:"create"});const registered=store.register(bundle()),claim=store.claim({request:registered.bundle.request,authorization:registered.bundle.authorization,claimedAt:t2});assert.equal(claim.disposition,"run_permitted");if(claim.disposition!=="run_permitted")throw new Error("claim unavailable");store.mark(claim.claim,t3);store.close();store=new SqliteAbsNewsLiveReadStoreV1(target.path,scope,{integrityKey:key,mode:"open"});assert.equal(store.recoverUnsettled(t4)[0]?.safeReasonCode,"restart_after_marker");assert.equal(store.recoverUnsettled(t4).length,0);store.close();const attacker=new DatabaseSync(target.path);attacker.exec("DELETE FROM abs_news_live_read_records WHERE kind='outcome'");attacker.close();assert.throws(()=>new SqliteAbsNewsLiveReadStoreV1(target.path,scope,{integrityKey:key,mode:"open"}),(error:unknown)=>error instanceof ProjectWorkspaceContractErrorV1&&error.safeCode==="integrity_failed");}finally{await rm(target.directory,{recursive:true,force:true});}});

test("CR9D-ABS-060 exact request boundary rejects digest drift, accessors, and Proxies without traps",()=>{const value=request();assert.throws(()=>parseAbsNewsLiveReadRequestV1({...value,maxTotalBytes:value.maxTotalBytes+1}),(error:unknown)=>error instanceof ProjectWorkspaceContractErrorV1&&error.safeCode==="digest_mismatch");let calls=0;const accessor={...value};Object.defineProperty(accessor,"requestId",{enumerable:true,get(){calls+=1;return value.requestId;}});assert.throws(()=>parseAbsNewsLiveReadRequestV1(accessor),ProjectWorkspaceContractErrorV1);assert.equal(calls,0);const proxied=observedProxy(value,"transparent");assert.throws(()=>parseAbsNewsLiveReadRequestV1(proxied.value),ProjectWorkspaceContractErrorV1);assert.equal(proxied.trapCount(),0);});
