import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { adaptPglite } from "../src/persistence/database.ts";
import { SecurityStore,type VerifiedAuthentication } from "../src/security/index.ts";
import { CONTROL_ROOM_IDEA_ADAPTER_V1,IdeaLabOwnerDecisionServiceErrorV1,IdeaLabOwnerDecisionServiceV1,IdeaLabProjectRegistryStoreV1,buildIdeaLabFixtureV1 } from "../src/idea-lab/v1/index.ts";

const key=new Uint8Array(32).fill(0x52),at="2026-08-31T16:08:00.000Z";
const authentication:VerifiedAuthentication={tenantId:"tenant:owner",provider:"test",subject:"owner-subject",verifiedAt:"2026-08-31T16:00:00.000Z",expiresAt:"2026-08-31T16:20:00.000Z"};
const intent={decision:"create_project" as const,safeReasonCode:"owner_promoted_for_validation",project:{projectId:"project:local-trades-ai-desk",workspaceName:"Local Trades AI Desk",title:"Validate an AI operations desk for local trades",summary:"Test demand, safety, and operating cost before any live customer automation is enabled.",projectKind:"business_validation",priority:72}};
async function setup(){const raw=new PGlite();for(const file of (await readdir(resolve("db/migrations"))).filter(f=>f.endsWith(".sql")).sort())await raw.exec(await readFile(resolve("db/migrations",file),"utf8"));await raw.query(`INSERT INTO tenants(id,display_name) VALUES ('tenant:owner','Owner')`);await raw.query(`INSERT INTO workspaces(id,tenant_id,display_name) VALUES ('workspace:control-room','tenant:owner','Control Room')`);await raw.query(`INSERT INTO adapter_registry(id,tenant_id,source_system,contract_version,authority_mode,status,project_types,supported_read_operations,supported_commands,redaction_policy_version,cursor_retention_days) VALUES($1,'tenant:owner','control_room_native_ideas','control-room-idea-lab-session/v1','control_room_native','fixture','["business_validation"]'::jsonb,'["read_project"]'::jsonb,'[]'::jsonb,'redaction-v1',30)`,[CONTROL_ROOM_IDEA_ADAPTER_V1]);
  const db=adaptPglite(raw),fixture=buildIdeaLabFixtureV1(),registry=new IdeaLabProjectRegistryStoreV1(db,key);await registry.registerSession(fixture.session);for(const c of fixture.contributions)await registry.recordContribution(c);await registry.recordSynthesis(fixture.synthesis);return{raw,db,fixture,registry};}

test("CR12B-IDEA-030 derives owner identity server-side and atomically promotes through an immutable permit",async()=>{const target=await setup();try{await new SecurityStore(target.db).bootstrapOwner({...authentication,identityId:"identity:owner",grantId:"grant:owner",displayName:"Owner",now:at});const service=new IdeaLabOwnerDecisionServiceV1(target.db,key);
  const result=await service.apply({sessionId:target.fixture.session.sessionId,intent,authentication,now:at});assert.equal(result.project?.projectId,intent.project.projectId);assert.notEqual(result.decision.ownerIdentityDigest,target.fixture.decision.ownerIdentityDigest);assert.equal(result.replayed,false);
  assert.equal((await target.raw.query(`SELECT * FROM control_policy_decisions`)).rows.length,1);assert.equal((await target.raw.query(`SELECT * FROM control_idea_owner_authorizations`)).rows.length,1);assert.equal((await target.raw.query(`SELECT * FROM control_idea_decisions`)).rows.length,1);
  const replay=await service.apply({sessionId:target.fixture.session.sessionId,intent,authentication,now:at});assert.equal(replay.replayed,true);assert.equal(replay.decision.decisionDigest,result.decision.decisionDigest);
}finally{await target.raw.close();}});

test("CR12B-IDEA-030 rejects operator-only, agent, and caller-minted identity paths without a project",async()=>{for(const mode of ["operator","agent"] as const){const target=await setup();try{if(mode==="operator"){await target.raw.query(`INSERT INTO control_identities(id,tenant_id,actor_type,display_name,auth_provider,auth_subject_digest,state,created_at,updated_at) VALUES('identity:operator','tenant:owner','human','Operator','test',$1,'active',$2,$2)`,[(await import("../src/security/index.ts")).sha256Digest({provider:"test",subject:"owner-subject"}),authentication.verifiedAt]);await target.raw.query(`INSERT INTO control_role_grants(id,tenant_id,identity_id,role_key,allowed_actions,project_ids,risk_ceiling,allow_external_effects,require_strong_factor,created_at,updated_at) VALUES('grant:operator','tenant:owner','identity:operator','operator','["*"]'::jsonb,'["*"]'::jsonb,'critical',false,false,$1,$1)`,[authentication.verifiedAt]);}else{await target.raw.query(`INSERT INTO control_identities(id,tenant_id,actor_type,display_name,auth_provider,auth_subject_digest,state,created_at,updated_at) VALUES('identity:agent','tenant:owner','agent','Agent','test',$1,'active',$2,$2)`,[(await import("../src/security/index.ts")).sha256Digest({provider:"test",subject:"owner-subject"}),authentication.verifiedAt]);await target.raw.query(`INSERT INTO control_role_grants(id,tenant_id,identity_id,role_key,allowed_actions,project_ids,risk_ceiling,allow_external_effects,require_strong_factor,created_at,updated_at) VALUES('grant:owner-agent','tenant:owner','identity:agent','owner','["*"]'::jsonb,'["*"]'::jsonb,'critical',false,false,$1,$1)`,[authentication.verifiedAt]);}
    await assert.rejects(new IdeaLabOwnerDecisionServiceV1(target.db,key).apply({sessionId:target.fixture.session.sessionId,intent,authentication,now:at}),e=>e instanceof IdeaLabOwnerDecisionServiceErrorV1&&(e.safeCode==="owner_forbidden"||e.safeCode==="owner_boundary_unavailable"));
    await assert.rejects(new IdeaLabOwnerDecisionServiceV1(target.db,key).apply({sessionId:target.fixture.session.sessionId,intent:{...intent,ownerIdentityDigest:`sha256:${"f".repeat(64)}`},authentication,now:at}),e=>e instanceof IdeaLabOwnerDecisionServiceErrorV1&&e.safeCode==="invalid_owner_decision");assert.equal((await target.raw.query(`SELECT * FROM projects`)).rows.length,0);
  }finally{await target.raw.close();}}});

test("CR12B-IDEA-030 refuses direct authorized persistence without a matching owner permit",async()=>{const target=await setup();try{await assert.rejects(target.registry.recordAuthorizedDecision(target.fixture.decision,`sha256:${"a".repeat(64)}`));assert.equal((await target.raw.query(`SELECT * FROM projects`)).rows.length,0);}finally{await target.raw.close();}});
