import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { adaptPglite } from "../src/persistence/database.ts";
import { SecurityStore,sha256Digest,type VerifiedAuthentication } from "../src/security/index.ts";
import { CONTROL_ROOM_IDEA_ADAPTER_V1,IdeaLabProjectLifecycleServiceErrorV1,IdeaLabProjectLifecycleServiceV1,IdeaLabProjectRegistryStoreV1,buildIdeaLabFixtureV1 } from "../src/idea-lab/v1/index.ts";
const key=new Uint8Array(32).fill(0x52),times=["2026-08-31T16:00:00.000Z","2026-08-31T16:10:00.000Z","2026-08-31T16:11:00.000Z","2026-08-31T16:12:00.000Z","2026-08-31T16:13:00.000Z","2026-08-31T16:14:00.000Z"],authentication:VerifiedAuthentication={tenantId:"tenant:owner",provider:"test",subject:"owner",verifiedAt:times[0]!,expiresAt:"2026-08-31T17:00:00.000Z"};
async function setup(){const raw=new PGlite();for(const file of(await readdir(resolve("db/migrations"))).filter(file=>file.endsWith(".sql")).sort())await raw.exec(await readFile(resolve("db/migrations",file),"utf8"));await raw.query(`INSERT INTO tenants(id,display_name) VALUES ('tenant:owner','Owner')`);await raw.query(`INSERT INTO workspaces(id,tenant_id,display_name) VALUES ('workspace:control-room','tenant:owner','Control Room')`);await raw.query(`INSERT INTO adapter_registry(id,tenant_id,source_system,contract_version,authority_mode,status,project_types,supported_read_operations,supported_commands,redaction_policy_version,cursor_retention_days) VALUES($1,'tenant:owner','control_room_native_ideas','control-room-idea-lab-session/v1','control_room_native','fixture','["business_validation"]'::jsonb,'["read_project"]'::jsonb,'[]'::jsonb,'redaction-v1',30)`,[CONTROL_ROOM_IDEA_ADAPTER_V1]);const db=adaptPglite(raw),registry=new IdeaLabProjectRegistryStoreV1(db,key),fixture=buildIdeaLabFixtureV1();await registry.registerSession(fixture.session);for(const item of fixture.contributions)await registry.recordContribution(item);await registry.recordSynthesis(fixture.synthesis);const project=(await registry.recordDecision(fixture.decision)).project!;await new SecurityStore(db).bootstrapOwner({...authentication,identityId:"identity:owner",grantId:"grant:owner",displayName:"Owner",now:times[1]!});let current=times[1]!;const make=()=>new IdeaLabProjectLifecycleServiceV1(db,key,()=>current);return{raw,db,project,make,setTime(value:string){current=value;}};}
function command(projectId:string,version:number,action:"pause"|"resume"|"complete"|"archive"|"reopen",requestedAt:string,id:string=action){return{commandId:`command.idea.lifecycle:${id}`,projectId,expectedVersion:version,action,requestedAt};}
test("CR12B-IDEA-050 replays and resumes the complete reversible lifecycle across restart",async()=>{const target=await setup();try{let project=target.project;for(const[action,time]of[["pause",times[1]],["resume",times[2]],["complete",times[3]],["archive",times[4]],["reopen",times[5]]]as const){target.setTime(time!);const input=command(project.projectId,project.version,action,time!),next=await target.make().transition(input,authentication),replay=await target.make().transition(input,authentication);assert.equal(replay.projectionDigest,next.projectionDigest);project=next;}assert.equal(project.lifecycleState,"active");assert.equal(project.version,6);assert.equal((await target.raw.query(`SELECT * FROM control_project_lifecycle_events`)).rows.length,6);}finally{await target.raw.close();}});
test("CR12B-IDEA-050 concurrent commands advance one version at most",async()=>{const target=await setup();try{target.setTime(times[1]!);const results=await Promise.allSettled([target.make().transition(command(target.project.projectId,1,"pause",times[1]!,"race-pause"),authentication),target.make().transition(command(target.project.projectId,1,"complete",times[1]!,"race-complete"),authentication)]);assert.equal(results.filter(item=>item.status==="fulfilled").length,1);assert.equal(results.filter(item=>item.status==="rejected"&&item.reason instanceof IdeaLabProjectLifecycleServiceErrorV1&&item.reason.safeCode==="state_conflict").length,1);assert.equal((await target.raw.query(`SELECT * FROM control_project_lifecycle_events`)).rows.length,2);}finally{await target.raw.close();}});
test("CR12B-IDEA-050 rejects illegal, stale, and caller-scoped lifecycle commands",async()=>{const target=await setup();try{target.setTime(times[1]!);await assert.rejects(target.make().transition({...command(target.project.projectId,1,"archive",times[1]!),tenantId:"tenant:spoof"},authentication),error=>error instanceof IdeaLabProjectLifecycleServiceErrorV1&&error.safeCode==="invalid_lifecycle_request");await assert.rejects(target.make().transition(command(target.project.projectId,1,"archive",times[1]!),authentication),error=>error instanceof IdeaLabProjectLifecycleServiceErrorV1&&error.safeCode==="state_conflict");assert.equal((await target.raw.query(`SELECT * FROM control_project_lifecycle_events`)).rows.length,1);}finally{await target.raw.close();}});
test("CR12B-IDEA-050 an operator cannot impersonate the owner for project lifecycle",async()=>{const target=await setup();try{const operatorAuth={...authentication,subject:"operator"};await target.raw.query(`INSERT INTO control_identities(id,tenant_id,actor_type,display_name,auth_provider,auth_subject_digest,state,created_at,updated_at) VALUES('identity:operator','tenant:owner','human','Operator','test',$1,'active',$2,$2)`,[sha256Digest({provider:"test",subject:"operator"}),times[0]]);await target.raw.query(`INSERT INTO control_role_grants(id,tenant_id,identity_id,role_key,allowed_actions,project_ids,risk_ceiling,allow_external_effects,require_strong_factor,created_at,updated_at) VALUES('grant:operator','tenant:owner','identity:operator','operator','["*"]'::jsonb,'["*"]'::jsonb,'critical',false,false,$1,$1)`,[times[0]]);target.setTime(times[1]!);await assert.rejects(target.make().transition(command(target.project.projectId,1,"pause",times[1]!),operatorAuth),error=>error instanceof IdeaLabProjectLifecycleServiceErrorV1&&error.safeCode==="owner_forbidden");assert.equal((await target.raw.query(`SELECT * FROM control_project_lifecycle_events`)).rows.length,1);}finally{await target.raw.close();}});
