import assert from "node:assert/strict";
import test from "node:test";
import { GET as defaultCatalog,createIdeaLabSessionCatalogHandlerV1 } from "../app/api/v1/idea-lab/sessions/route.ts";
import { GET as defaultDetail,createIdeaLabSessionDetailHandlerV1 } from "../app/api/v1/idea-lab/sessions/[sessionId]/route.ts";
import { POST as defaultLifecycle,createIdeaLabProjectLifecycleHandlerV1 } from "../app/api/v1/idea-lab/projects/[projectId]/lifecycle/[action]/route.ts";
import { GET as defaultProject,createIdeaLabProjectReadHandlerV1 } from "../app/api/v1/idea-lab/projects/[projectId]/route.ts";
import type { IdeaLabProtectedRuntimeV1 } from "../app/idea-lab-protected-runtime.ts";
import type { VerifiedAuthentication } from "../src/security/index.ts";
import { buildIdeaLabFixtureV1 } from "../src/idea-lab/v1/index.ts";
const sessionId="idea-session:resume-api",projectId="project:resume-api",auth:VerifiedAuthentication={tenantId:"tenant:owner",provider:"test",subject:"owner",verifiedAt:"2026-08-31T16:00:00.000Z",expiresAt:"2026-08-31T17:00:00.000Z"};
const getRequest=new Request("http://localhost/api/v1/idea-lab/sessions"),sessionContext={params:Promise.resolve({sessionId})},projectContext={params:Promise.resolve({projectId})},lifecycleContext={params:Promise.resolve({projectId,action:"pause"})};
function post(body:unknown){return new Request("http://localhost/api/v1/idea-lab/lifecycle",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});}
test("CR12B-IDEA-050 catalog, detail, project, and lifecycle endpoints are default closed",async()=>{for(const response of[await defaultCatalog(getRequest),await defaultDetail(getRequest,sessionContext),await defaultProject(getRequest,projectContext),await defaultLifecycle(post({}),lifecycleContext)]){assert.equal(response.status,503);assert.equal(response.headers.get("cache-control"),"no-store");}});
test("CR12B-IDEA-050 authenticates reads before service access and keeps route scope server-owned",async()=>{let calls=0;const blocked={ownerSession:{async verify(){throw new Error("no session");}},operatorService:{async list(){calls+=1;return[];}}}as unknown as IdeaLabProtectedRuntimeV1;assert.equal((await createIdeaLabSessionCatalogHandlerV1(blocked)(getRequest)).status,401);assert.equal(calls,0);let received:unknown;const configured={ownerSession:{async verify(){return auth;}},operatorService:{async get(id:unknown,authentication:VerifiedAuthentication){received={id,authentication};return{sessionId:id,state:"ready"};}}}as unknown as IdeaLabProtectedRuntimeV1;assert.equal((await createIdeaLabSessionDetailHandlerV1(configured)(getRequest,sessionContext)).status,200);assert.deepEqual(received,{id:sessionId,authentication:auth});});
test("CR12B-IDEA-050 lifecycle route rejects aliases and supplies only path project/action",async()=>{let received:unknown;const runtime={ownerSession:{async verify(){return auth;}},lifecycleService:{async transition(input:unknown,authentication:VerifiedAuthentication){received={input,authentication};return{projectId,lifecycleState:"paused",version:2};}}}as unknown as IdeaLabProtectedRuntimeV1,handler=createIdeaLabProjectLifecycleHandlerV1(runtime);const alias=await handler(post({commandId:"command.idea.lifecycle:api",expectedVersion:1,requestedAt:"2026-08-31T16:01:00.000Z",projectId:"project:spoof"}),lifecycleContext);assert.equal(alias.status,400);const good=await handler(post({commandId:"command.idea.lifecycle:api",expectedVersion:1,requestedAt:"2026-08-31T16:01:00.000Z"}),lifecycleContext);assert.equal(good.status,200);assert.deepEqual((received as{input:unknown}).input,{commandId:"command.idea.lifecycle:api",expectedVersion:1,requestedAt:"2026-08-31T16:01:00.000Z",projectId,action:"pause"});assert.deepEqual((received as{authentication:VerifiedAuthentication}).authentication,auth);});
test("CR12B-IDEA-060 project read returns matched protected project and workspace identities",async()=>{const project={...buildIdeaLabFixtureV1().promotedProject,projectId},runtime={ownerSession:{async verify(){return auth;}},lifecycleService:{async get(id:unknown,authentication:VerifiedAuthentication){assert.equal(id,projectId);assert.deepEqual(authentication,auth);return project;}}}as unknown as IdeaLabProtectedRuntimeV1,response=await createIdeaLabProjectReadHandlerV1(runtime)(getRequest,projectContext),body=await response.json()as{project:{projectId:string};workspace:{projectId:string}};assert.equal(response.status,200);assert.equal(body.project.projectId,projectId);assert.equal(body.workspace.projectId,projectId);});
