import assert from "node:assert/strict";
import test from "node:test";
import { POST as defaultCreate,createIdeaLabSessionHandlerV1 } from "../app/api/v1/idea-lab/sessions/route.ts";
import { POST as defaultStart,createIdeaLabStartHandlerV1 } from "../app/api/v1/idea-lab/sessions/[sessionId]/start/route.ts";
import { POST as defaultCancel } from "../app/api/v1/idea-lab/sessions/[sessionId]/cancel/route.ts";
import { POST as defaultSynthesis } from "../app/api/v1/idea-lab/sessions/[sessionId]/synthesis/route.ts";
import type { IdeaLabProtectedRuntimeV1 } from "../app/idea-lab-protected-runtime.ts";
import type { VerifiedAuthentication } from "../src/security/index.ts";
const sessionId="idea-session:operator-api",context={params:Promise.resolve({sessionId})},auth:VerifiedAuthentication={tenantId:"tenant:owner",provider:"test",subject:"owner",verifiedAt:"2026-08-31T16:00:00.000Z",expiresAt:"2026-08-31T17:00:00.000Z"};
function request(url:string,body:unknown,headers:Record<string,string>={}){return new Request(url,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});}
test("CR12B-IDEA-040 all shipped operator endpoints are default closed",async()=>{const command={commandId:"command.idea:closed",requestedAt:"2026-08-31T16:01:00.000Z"};for(const response of[await defaultCreate(request("http://localhost/api/v1/idea-lab/sessions",{})),await defaultStart(request(`http://localhost/x/${sessionId}/start`,command),context),await defaultCancel(request(`http://localhost/x/${sessionId}/cancel`,command),context),await defaultSynthesis(request(`http://localhost/x/${sessionId}/synthesis`,command),context)]){assert.equal(response.status,503);assert.equal(response.headers.get("cache-control"),"no-store");}});
test("CR12B-IDEA-040 authentication happens before any protected operator service call",async()=>{let calls=0;const runtime={ownerSession:{async verify(){throw new Error("no session");}},operatorService:{async create(){calls+=1;return{};}}}as unknown as IdeaLabProtectedRuntimeV1;const response=await createIdeaLabSessionHandlerV1(runtime)(request("http://localhost/api/v1/idea-lab/sessions",{}));assert.equal(response.status,401);assert.equal(calls,0);});
test("CR12B-IDEA-040 route scope overrides no browser field and rejects command aliases",async()=>{let received:unknown;const runtime={ownerSession:{async verify(credential:unknown){assert.ok(credential instanceof Request);return auth;}},operatorService:{async start(input:unknown,authentication:VerifiedAuthentication){received={input,authentication};return{sessionId,state:"panel_complete"};}}}as unknown as IdeaLabProtectedRuntimeV1,handler=createIdeaLabStartHandlerV1(runtime);const aliased=await handler(request(`http://localhost/x/${sessionId}/start`,{commandId:"command.idea:api",requestedAt:"2026-08-31T16:01:00.000Z",sessionId:"idea-session:spoof"}),context);assert.equal(aliased.status,400);const good=await handler(request(`http://localhost/x/${sessionId}/start`,{commandId:"command.idea:api",requestedAt:"2026-08-31T16:01:00.000Z"},{"x-control-room-tenant-id":"tenant:spoof"}),context);assert.equal(good.status,200);assert.equal((received as{input:{sessionId:string}}).input.sessionId,sessionId);assert.deepEqual((received as{authentication:VerifiedAuthentication}).authentication,auth);});
test("CR12B-IDEA-040 rejects oversized and non-JSON bodies before the operator service",async()=>{let calls=0;const runtime={ownerSession:{async verify(){return auth;}},operatorService:{async create(){calls+=1;return{};}}}as unknown as IdeaLabProtectedRuntimeV1,handler=createIdeaLabSessionHandlerV1(runtime);const oversized=await handler(request("http://localhost/api/v1/idea-lab/sessions",{padding:"x".repeat(9000)}));assert.equal(oversized.status,400);const wrongType=await handler(new Request("http://localhost/api/v1/idea-lab/sessions",{method:"POST",headers:{"content-type":"text/plain"},body:"{}"}));assert.equal(wrongType.status,400);assert.equal(calls,0);});
