import assert from "node:assert/strict";
import test from "node:test";
import { POST,createIdeaLabOwnerDecisionHandlerV1 } from "../app/api/v1/idea-lab/sessions/[sessionId]/decision/route.ts";
import type { IdeaLabProtectedRuntimeV1 } from "../app/idea-lab-protected-runtime.ts";
import type { VerifiedAuthentication } from "../src/security/index.ts";

const sessionId="idea-session:api",context={params:Promise.resolve({sessionId})},auth:VerifiedAuthentication={tenantId:"tenant:owner",provider:"test",subject:"owner",verifiedAt:"2026-08-31T16:00:00.000Z",expiresAt:"2026-08-31T17:00:00.000Z"};
test("CR12B-IDEA-030 default owner endpoint is closed and ignores identity headers",async()=>{const response=await POST(new Request(`http://localhost/api/v1/idea-lab/sessions/${sessionId}/decision`,{method:"POST",headers:{"content-type":"application/json","x-control-room-tenant-id":"tenant:spoof","oai-authenticated-user-id":"identity:spoof"},body:JSON.stringify({decision:"save",safeReasonCode:"save"})}),context);assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:"protected_owner_boundary_unavailable"});});
test("CR12B-IDEA-030 configured endpoint verifies the opaque request before owner decision service",async()=>{let serviceCalls=0;const runtime={ownerSession:{async verify(){throw new Error("no session");}},ownerDecisionService:{async apply(){serviceCalls+=1;throw new Error("unreachable");}}} as unknown as IdeaLabProtectedRuntimeV1;const response=await createIdeaLabOwnerDecisionHandlerV1(runtime)(new Request(`http://localhost/api/v1/idea-lab/sessions/${sessionId}/decision`,{method:"POST",body:"{}"}),context);assert.equal(response.status,401);assert.equal(serviceCalls,0);});
test("CR12B-IDEA-030 configured endpoint passes only verified auth, route session, and exact intent",async()=>{let received:unknown;const runtime={ownerSession:{async verify(credential:unknown){assert.ok(credential instanceof Request);return auth;}},ownerDecisionService:{async apply(input:unknown){received=input;return{decision:{contractVersion:"control-room-idea-lab-decision/v1",decisionId:"decision.idea:api"},replayed:false,authorization:{policyDecisionId:"policy.idea:api",permitDigest:`sha256:${"a".repeat(64)}`}};}}} as unknown as IdeaLabProtectedRuntimeV1;const intent={decision:"save",safeReasonCode:"owner_saved"};const response=await createIdeaLabOwnerDecisionHandlerV1(runtime)(new Request(`http://localhost/api/v1/idea-lab/sessions/${sessionId}/decision`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(intent)}),context);assert.equal(response.status,201);assert.deepEqual((received as {sessionId:string;intent:unknown;authentication:VerifiedAuthentication}).sessionId,sessionId);assert.deepEqual((received as {intent:unknown}).intent,intent);assert.deepEqual((received as {authentication:VerifiedAuthentication}).authentication,auth);});
