import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { adaptPglite } from "../src/persistence/database.ts";
import { SecurityStore,sha256Digest,type VerifiedAuthentication } from "../src/security/index.ts";
import { CONTROL_ROOM_IDEA_ADAPTER_V1,DeterministicIdeaLabFakeDriverV1,IdeaLabOperatorServiceErrorV1,
  IdeaLabOwnerDecisionServiceV1,IdeaLabProtectedOperatorServiceV1,buildIdeaLabFixtureV1 } from "../src/idea-lab/v1/index.ts";

const key=new Uint8Array(32).fill(0x61),times=["2026-08-31T16:00:00.000Z","2026-08-31T16:01:00.000Z","2026-08-31T16:02:00.000Z","2026-08-31T16:03:00.000Z","2026-08-31T16:04:00.000Z"];
const authentication:VerifiedAuthentication={tenantId:"tenant:owner",provider:"test",subject:"owner",verifiedAt:times[0]!,expiresAt:"2026-08-31T16:20:00.000Z"};
const createInput={commandId:"command.idea:create-1",title:"AI desk for independent electricians",ideaSummary:"Help owner-operated electrical businesses respond to leads and prepare safe follow-up drafts.",targetCustomer:"Independent electrical contractors",maxRounds:1,maxDurationSeconds:300,maxCostUsd:2,requestedAt:times[1]!};
async function setup(){const raw=new PGlite();for(const file of(await readdir(resolve("db/migrations"))).filter(file=>file.endsWith(".sql")).sort())await raw.exec(await readFile(resolve("db/migrations",file),"utf8"));await raw.query(`INSERT INTO tenants(id,display_name) VALUES ('tenant:owner','Owner')`);await raw.query(`INSERT INTO workspaces(id,tenant_id,display_name) VALUES ('workspace:control-room','tenant:owner','Control Room')`);await raw.query(`INSERT INTO adapter_registry(id,tenant_id,source_system,contract_version,authority_mode,status,project_types,supported_read_operations,supported_commands,redaction_policy_version,cursor_retention_days) VALUES($1,'tenant:owner','control_room_native_ideas','control-room-idea-lab-session/v1','control_room_native','fixture','["business_validation"]'::jsonb,'["read_project"]'::jsonb,'[]'::jsonb,'redaction-v1',30)`,[CONTROL_ROOM_IDEA_ADAPTER_V1]);const db=adaptPglite(raw),fixture=buildIdeaLabFixtureV1();let current=times[1]!;const calls={count:0},fake=new DeterministicIdeaLabFakeDriverV1(),driver={mode:"repository_fake" as const,async invoke(input:Parameters<DeterministicIdeaLabFakeDriverV1["invoke"]>[0]){calls.count+=1;return fake.invoke(input);}};const service=new IdeaLabProtectedOperatorServiceV1(db,key,{workspaceId:"workspace:control-room",participants:fixture.session.participants,driver,clock:()=>current});return{raw,db,service,calls,setTime(value:string){current=value;}};}
async function owner(target:Awaited<ReturnType<typeof setup>>){await new SecurityStore(target.db).bootstrapOwner({...authentication,identityId:"identity:owner",grantId:"grant:owner",displayName:"Owner",now:times[1]!});}

test("CR12B-IDEA-040 creates, runs, synthesizes, and owner-promotes one monitored project",async()=>{const target=await setup();try{await owner(target);const created=await target.service.create(createInput,authentication);assert.equal(created.state,"ready");assert.equal(created.providerContacted,false);
  target.setTime(times[2]!);const started=await target.service.start({commandId:"command.idea:start-1",sessionId:created.sessionId,requestedAt:times[2]},authentication);assert.equal(started.state,"panel_complete");assert.equal(started.messagesUsed,4);assert.equal(target.calls.count,4);
  target.setTime(times[3]!);const synthesized=await target.service.synthesize({commandId:"command.idea:synthesis-1",sessionId:created.sessionId,requestedAt:times[3]},authentication);assert.equal(synthesized.state,"synthesized");assert.ok(synthesized.synthesisDigest);
  target.setTime(times[4]!);const result=await new IdeaLabOwnerDecisionServiceV1(target.db,key).apply({sessionId:created.sessionId,intent:{decision:"create_project",safeReasonCode:"owner_promoted_for_validation",project:{projectId:"project:electrician-ai-desk",workspaceName:"Electrician AI Desk",title:"Validate electrician AI desk",summary:"Validate demand and safe operating boundaries.",projectKind:"business_validation",priority:65}},authentication,now:times[4]!});assert.equal(result.project?.projectId,"project:electrician-ai-desk");const final=await target.service.current(await (async()=>{const row=await target.raw.query<{payload:unknown}>(`SELECT payload FROM control_idea_sessions WHERE session_id=$1`,[created.sessionId]);return row.rows[0]!.payload;})());assert.equal(final.state,"decided");assert.equal(final.projectId,"project:electrician-ai-desk");assert.equal((await target.raw.query(`SELECT * FROM control_outbox`)).rows.length,0);
}finally{await target.raw.close();}});

test("CR12B-IDEA-040 exact command replay never repeats a panel call or synthesis",async()=>{const target=await setup();try{await owner(target);const first=await target.service.create(createInput,authentication),replayedCreate=await target.service.create(createInput,authentication);assert.equal(replayedCreate.sessionDigest,first.sessionDigest);
  target.setTime(times[2]!);const command={commandId:"command.idea:start-replay",sessionId:first.sessionId,requestedAt:times[2]!},run=await target.service.start(command,authentication),replay=await target.service.start(command,authentication);assert.equal(replay.runDigest,run.runDigest);assert.equal(target.calls.count,4);
  target.setTime(times[3]!);const synthCommand={commandId:"command.idea:synth-replay",sessionId:first.sessionId,requestedAt:times[3]!},synthesis=await target.service.synthesize(synthCommand,authentication);target.setTime(times[4]!);const synthesisReplay=await target.service.synthesize(synthCommand,authentication);assert.equal(synthesisReplay.synthesisDigest,synthesis.synthesisDigest);assert.equal((await target.raw.query(`SELECT * FROM control_idea_syntheses`)).rows.length,1);
}finally{await target.raw.close();}});

test("CR12B-IDEA-040 cancellation before provider evidence is durable and prevents a later start",async()=>{const target=await setup();try{await owner(target);const created=await target.service.create({...createInput,commandId:"command.idea:create-cancel"},authentication);target.setTime(times[2]!);const cancelled=await target.service.cancel({commandId:"command.idea:cancel-1",sessionId:created.sessionId,requestedAt:times[2]!},authentication);assert.equal(cancelled.state,"cancelled");assert.equal(cancelled.safeStatusCode,"cancelled_before_provider");const start=await target.service.start({commandId:"command.idea:start-after-cancel",sessionId:created.sessionId,requestedAt:times[2]!},authentication);assert.equal(start.state,"cancelled");assert.equal(target.calls.count,0);
}finally{await target.raw.close();}});

test("CR12B-IDEA-040 rejects caller scope, stale commands, and synthesis before a complete panel",async()=>{const target=await setup();try{await owner(target);await assert.rejects(target.service.create({...createInput,tenantId:"tenant:spoof"},authentication),error=>error instanceof IdeaLabOperatorServiceErrorV1&&error.safeCode==="invalid_operator_request");target.setTime(times[4]!);await assert.rejects(target.service.create({...createInput,commandId:"command.idea:stale",requestedAt:"2026-08-31T15:00:00.000Z"},authentication),error=>error instanceof IdeaLabOperatorServiceErrorV1&&error.safeCode==="invalid_operator_request");target.setTime(times[1]!);const created=await target.service.create({...createInput,commandId:"command.idea:no-panel"},authentication);target.setTime(times[2]!);await assert.rejects(target.service.synthesize({commandId:"command.idea:early-synthesis",sessionId:created.sessionId,requestedAt:times[2]!},authentication),error=>error instanceof IdeaLabOperatorServiceErrorV1&&error.safeCode==="state_conflict");
}finally{await target.raw.close();}});

test("CR12B-IDEA-040 only a human owner can create an idea session",async()=>{for(const actor of["operator","agent"]as const){const target=await setup();try{const identityId=`identity:${actor}`,actorType=actor==="agent"?"agent":"human",role=actor==="operator"?"operator":"owner";await target.raw.query(`INSERT INTO control_identities(id,tenant_id,actor_type,display_name,auth_provider,auth_subject_digest,state,created_at,updated_at) VALUES($1,'tenant:owner',$2,$3,'test',$4,'active',$5,$5)`,[identityId,actorType,actor,sha256Digest({provider:"test",subject:"owner"}),times[0]]);await target.raw.query(`INSERT INTO control_role_grants(id,tenant_id,identity_id,role_key,allowed_actions,project_ids,risk_ceiling,allow_external_effects,require_strong_factor,created_at,updated_at) VALUES($1,'tenant:owner',$2,$3,'["*"]'::jsonb,'["*"]'::jsonb,'critical',false,false,$4,$4)`,[`grant:${actor}`,identityId,role,times[0]]);await assert.rejects(target.service.create({...createInput,commandId:`command.idea:${actor}`},authentication),error=>error instanceof IdeaLabOperatorServiceErrorV1);assert.equal((await target.raw.query(`SELECT * FROM control_idea_sessions`)).rows.length,0);}finally{await target.raw.close();}}});
