import assert from "node:assert/strict";
import test from "node:test";
import {sha256Digest} from "../src/security/digest";
import {createHostResultCollectorV1} from "../src/security/host-value";
import {BitwardenSecretProviderV1,DestinationNativeSecretProviderV1,OnePasswordSecretProviderV1,type CliProviderConfigurationV1,type InjectedProviderRunnerV1,type NodeLocalSecretProviderV1,type ProviderCommandPlanV1,type ProviderRunnerResultV1,type SecretProviderAcquisitionV1} from "../src/secret-broker/v1";
import {binaryViewAttack,observedProxy,type BinaryViewAttackMode,type ObservedProxyMode} from "./proxy-test-helper";

const digest=(label:string)=>sha256Digest({label}),credentialRef="credential:publishing",binaryDigest=digest("pinned-binary"),stderrDigest=digest("stderr-empty");
const referenceDigest=(providerReference:string)=>sha256Digest({providerReference});
function config(providerReference:string,overrides:Partial<CliProviderConfigurationV1>={}):CliProviderConfigurationV1{return{executablePath:"/opt/control-room/bin/provider",expectedBinaryDigest:binaryDigest,timeoutMilliseconds:5_000,maximumOutputBytes:1_024,bindings:[{credentialRef,providerReference,providerReferenceDigest:referenceDigest(providerReference)}],...overrides};}
class FakeRunner implements InjectedProviderRunnerV1{plans:ProviderCommandPlanV1[]=[];constructor(private readonly result:(plan:ProviderCommandPlanV1)=>ProviderRunnerResultV1){}async run(plan:ProviderCommandPlanV1,collector:{submit(value:unknown):void}){this.plans.push(structuredClone(plan));collector.submit(this.result(plan));}}
async function acquire(provider:NodeLocalSecretProviderV1,input:{credentialRef:string;providerReferenceDigest:string;invocationId:string}){const result=createHostResultCollectorV1();await provider.acquire(input,result.collector);return result.take() as SecretProviderAcquisitionV1;}

test("CR8E Bitwarden adapter freezes exact-id no-shell noninteractive command planning",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000",stdout=new TextEncoder().encode("synthetic-provider-material\r\n"),runner=new FakeRunner(()=>({status:"completed",exitCode:0,stdout,observedBinaryDigest:binaryDigest,stderrDigest})),provider=new BitwardenSecretProviderV1(config(itemId),runner);
  const result=await acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:"invocation:one"});assert.equal(result.status,"resolved");if(result.status!=="resolved")return;assert.equal(new TextDecoder().decode(result.material),"synthetic-provider-material");assert.ok(stdout.every((byte)=>byte===0));assert.deepEqual(runner.plans[0],{executablePath:"/opt/control-room/bin/provider",expectedBinaryDigest:binaryDigest,args:["get","password",itemId,"--nointeraction"],shell:false,interactive:false,inheritEnvironment:false,stdin:"none",timeoutMilliseconds:5_000,maximumOutputBytes:1_024});await result.release();assert.ok(result.material.every((byte)=>byte===0));
});

test("CR8E 1Password adapter uses one private reference and no-newline output",async()=>{const locator="op://Automation/Publisher/token",runner=new FakeRunner(()=>({status:"completed",exitCode:0,stdout:new TextEncoder().encode("synthetic-onepassword-material"),observedBinaryDigest:binaryDigest,stderrDigest})),provider=new OnePasswordSecretProviderV1(config(locator),runner);
  const result=await acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(locator),invocationId:"invocation:one"});assert.equal(result.status,"resolved");assert.deepEqual(runner.plans[0].args,["read",locator,"--no-newline"]);assert.equal(runner.plans[0].shell,false);assert.equal(runner.plans[0].inheritEnvironment,false);
});

test("CR8E provider adapters require exact private locators and matching locator digests",async()=>{assert.throws(()=>new BitwardenSecretProviderV1(config("Github"),new FakeRunner(()=>({status:"not_started",safeCode:"missing"}))),/binding invalid/);assert.throws(()=>new OnePasswordSecretProviderV1(config("op://vault/item"),new FakeRunner(()=>({status:"not_started",safeCode:"missing"}))),/binding invalid/);
  const itemId="123e4567-e89b-12d3-a456-426614174000",mutable=config(itemId),runner=new FakeRunner(()=>{throw new Error("must not run");}),provider=new BitwardenSecretProviderV1(mutable,runner);mutable.bindings[0].providerReference="aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa";assert.deepEqual(await acquire(provider,{credentialRef,providerReferenceDigest:digest("wrong"),invocationId:"invocation:one"}),{status:"unavailable",safeCode:"missing"});assert.equal(runner.plans.length,0);assert.throws(()=>new BitwardenSecretProviderV1({...config(itemId),unexpected:"value"} as never,runner),/configuration invalid/);
});

test("CR8E pinned binary mismatch and oversized output fail closed and zero captured bytes",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000";for(const mode of ["binary","oversize"] as const){const stdout=new Uint8Array(mode==="oversize"?1_025:20).fill(0x71),runner=new FakeRunner(()=>({status:"completed",exitCode:0,stdout,observedBinaryDigest:mode==="binary"?digest("wrong-binary"):binaryDigest,stderrDigest})),provider=new BitwardenSecretProviderV1(config(itemId),runner);await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:`invocation:${mode}`}),/binary identity|output bound/);assert.ok(stdout.every((byte)=>byte===0));}}
);

test("CR8E typed not-started and nonzero outcomes return bounded denial without material",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000";let runner=new FakeRunner(()=>({status:"not_started",safeCode:"unavailable_platform"})),provider=new BitwardenSecretProviderV1(config(itemId),runner);assert.deepEqual(await acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:"invocation:none"}),{status:"unavailable",safeCode:"unavailable_platform"});
  const stdout=new TextEncoder().encode("hostile-provider-error-material");runner=new FakeRunner(()=>({status:"completed",exitCode:2,stdout,observedBinaryDigest:binaryDigest,stderrDigest,safeCode:"locked"}));provider=new BitwardenSecretProviderV1(config(itemId),runner);assert.deepEqual(await acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:"invocation:locked"}),{status:"unavailable",safeCode:"locked"});assert.ok(stdout.every((byte)=>byte===0));
});

test("CR8E unknown runner outcome remains ambiguous to the broker caller",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000",runner=new FakeRunner(()=>({status:"outcome_unknown",safeCode:"runner_disconnected"})),provider=new BitwardenSecretProviderV1(config(itemId),runner);await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:"invocation:unknown"}),/outcome unknown/);});

test("CR8E malformed runner envelopes fail closed and zero any captured output",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000";for(const mode of ["extra","unsafe_code","success_code"] as const){const stdout=new TextEncoder().encode("synthetic-malformed-output"),runner=new FakeRunner(()=>mode==="extra"?{status:"completed",exitCode:0,stdout,observedBinaryDigest:binaryDigest,stderrDigest,extra:"forbidden"} as never:mode==="unsafe_code"?{status:"not_started",safeCode:"password=forbidden",stdout} as never:{status:"completed",exitCode:0,stdout,observedBinaryDigest:binaryDigest,stderrDigest,safeCode:"locked"});const provider=new BitwardenSecretProviderV1(config(itemId),runner);await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:`invocation:${mode}`}),/provider result invalid/);assert.ok(stdout.every((byte)=>byte===0));}}
);

test("CR8E provider result envelopes reject inherited, symbol, and accessor widening without invoking accessors",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000";for(const mode of ["inherited","symbol","accessor"] as const){let getterCalls=0;const stdout=new TextEncoder().encode(`synthetic-${mode}-output`);let value:Record<PropertyKey,unknown>;
    if(mode==="inherited")value=Object.assign(Object.create({status:"completed"}),{exitCode:0,stdout,observedBinaryDigest:binaryDigest,stderrDigest});
    else if(mode==="symbol")value={status:"completed",exitCode:0,stdout,observedBinaryDigest:binaryDigest,stderrDigest,[Symbol("hidden")]:true};
    else {value={status:"completed",stdout,observedBinaryDigest:binaryDigest,stderrDigest};Object.defineProperty(value,"exitCode",{enumerable:true,get(){getterCalls++;return 0;}});}
    const runner=new FakeRunner(()=>value as never),provider=new BitwardenSecretProviderV1(config(itemId),runner);await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:`invocation:${mode}`}),/provider result invalid/);assert.equal(getterCalls,0);assert.ok(stdout.every((byte)=>byte===0));
  }});

test("CR8E provider adapters capture runner and native resolver functions at construction",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000",runner=new FakeRunner(()=>({status:"not_started",safeCode:"locked"}));const provider=new BitwardenSecretProviderV1(config(itemId),runner);runner.run=async()=>{throw new Error("mutated runner must not run");};
  assert.deepEqual(await acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:"invocation:captured"}),{status:"unavailable",safeCode:"locked"});
  const locator="native://publishing/captured",resolver={async resolve(_input:unknown,result:{submit(value:unknown):void}){result.submit({status:"unavailable" as const,safeCode:"locked" as const});}},native=new DestinationNativeSecretProviderV1([{credentialRef,providerReference:locator,providerReferenceDigest:referenceDigest(locator)}],resolver);resolver.resolve=async()=>{throw new Error("mutated resolver must not run");};
  assert.deepEqual(await acquire(native,{credentialRef,providerReferenceDigest:referenceDigest(locator),invocationId:"invocation:native-captured"}),{status:"unavailable",safeCode:"locked"});
});

test("CR8E destination-native adapter exposes only the fixed resolver seam",async()=>{const locator="native://publishing/account-a",seen:Array<Record<string,string>>=[],provider=new DestinationNativeSecretProviderV1([{credentialRef,providerReference:locator,providerReferenceDigest:referenceDigest(locator)}],{async resolve(input,result){seen.push(input);result.submit({status:"unavailable",safeCode:"interaction_required"});}});assert.deepEqual(await acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(locator),invocationId:"invocation:native"}),{status:"unavailable",safeCode:"interaction_required"});assert.deepEqual(seen,[{credentialRef,providerReference:locator,invocationId:"invocation:native"}]);
});

test("CR8Q provider configuration, binding arrays, bindings, and runners reject Proxies with zero traps",()=>{const itemId="123e4567-e89b-12d3-a456-426614174000",runner=new FakeRunner(()=>({status:"not_started",safeCode:"missing"}));
  const configProxy=observedProxy(config(itemId),"throwing");assert.throws(()=>new BitwardenSecretProviderV1(configProxy.value,runner),/configuration invalid/);assert.equal(configProxy.trapCount(),0);
  const bindingArray=observedProxy(config(itemId).bindings,"throwing"),arrayConfig=config(itemId,{bindings:bindingArray.value});assert.throws(()=>new BitwardenSecretProviderV1(arrayConfig,runner),/configuration invalid/);assert.equal(bindingArray.trapCount(),0);
  const binding=observedProxy(config(itemId).bindings[0],"throwing"),bindingConfig=config(itemId,{bindings:[binding.value]});assert.throws(()=>new BitwardenSecretProviderV1(bindingConfig,runner),/binding invalid/);assert.equal(binding.trapCount(),0);
  const runnerProxy=observedProxy(runner,"throwing");assert.throws(()=>new BitwardenSecretProviderV1(config(itemId),runnerProxy.value),/runner invalid/);assert.equal(runnerProxy.trapCount(),0);
  const resolverProxy=observedProxy({async resolve(_input:unknown,result:{submit(value:unknown):void}){result.submit({status:"unavailable" as const,safeCode:"missing" as const});}},"throwing"),locator="native://publishing/proxy";assert.throws(()=>new DestinationNativeSecretProviderV1([{credentialRef,providerReference:locator,providerReferenceDigest:referenceDigest(locator)}],resolverProxy.value),/resolver invalid/);assert.equal(resolverProxy.trapCount(),0);
});

test("CR8Q runner-result Proxies execute zero traps and are never accepted as material",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000";for(const mode of ["transparent","key_hiding","descriptor_fabricating","throwing"] as ObservedProxyMode[]){const stdout=new Uint8Array([1,2,3]),target={status:"completed" as const,exitCode:0,stdout,observedBinaryDigest:binaryDigest,stderrDigest,...(mode==="key_hiding"?{[Symbol("hidden")]:true}:{})},result=observedProxy(target,mode),provider=new BitwardenSecretProviderV1(config(itemId),new FakeRunner(()=>result.value));
  await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:`invocation:proxy-runner:${mode}`}),/Proxy result rejected/);assert.equal(result.trapCount(),0);stdout.fill(0);
}
  const stdoutTarget=new Uint8Array([4,5,6]),stdoutProxy=observedProxy(stdoutTarget,"throwing"),provider=new BitwardenSecretProviderV1(config(itemId),new FakeRunner(()=>({status:"completed",exitCode:0,stdout:stdoutProxy.value,observedBinaryDigest:binaryDigest,stderrDigest})));
  await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:"invocation:proxy-stdout"}),/provider result invalid/);assert.equal(stdoutProxy.trapCount(),0);stdoutTarget.fill(0);
});

test("CR8Q runner collector misuse wipes the first accepted output",async()=>{const itemId="123e4567-e89b-12d3-a456-426614174000";for(const mode of ["double","throw_after"] as const){const stdout=new TextEncoder().encode(`runner-collector-${mode}`),runner:InjectedProviderRunnerV1={async run(_plan,collector){collector.submit({status:"completed",exitCode:0,stdout,observedBinaryDigest:binaryDigest,stderrDigest});if(mode==="double")collector.submit({status:"not_started",safeCode:"missing"});else throw new Error("after submit");}},provider=new BitwardenSecretProviderV1(config(itemId),runner);await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(itemId),invocationId:`invocation:runner-collector:${mode}`}),/collector conflict|after submit/);assert.ok(stdout.every((byte)=>byte===0));}});

test("CR8Q runner binary validation uses intrinsics and rejects shared, shadowed, detached, and widened views",async()=>{for(const providerKind of ["bitwarden","onepassword"] as const){const providerReference=providerKind==="bitwarden"?"123e4567-e89b-12d3-a456-426614174000":"op://Automation/Publisher/token";for(const mode of ["shared","buffer_getter","buffer_data","byte_length_getter","byte_length_data","subclass","prototype_drift","detached","backing_constructor_getter","method_getters","subview_offset","subview_prefix"] as BinaryViewAttackMode[]){const binary=binaryViewAttack(mode),runner=new FakeRunner(()=>({status:"completed",exitCode:0,stdout:binary.value,observedBinaryDigest:binaryDigest,stderrDigest})),provider=providerKind==="bitwarden"?new BitwardenSecretProviderV1(config(providerReference),runner):new OnePasswordSecretProviderV1(config(providerReference),runner);await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(providerReference),invocationId:`invocation:runner-binary:${providerKind}:${mode}`}),/provider result invalid/);assert.equal(binary.getterCount(),0);assert.equal(binary.isWiped(),true);}}});

test("CR8Q destination-native result Proxies execute zero traps and fail closed",async()=>{const locator="native://publishing/proxy-result";for(const mode of ["transparent","key_hiding","descriptor_fabricating","throwing"] as ObservedProxyMode[]){const material=new Uint8Array([7,8,9]),target={status:"resolved" as const,material,release:async()=>undefined,...(mode==="key_hiding"?{[Symbol("hidden")]:true}:{})},result=observedProxy(target,mode),provider=new DestinationNativeSecretProviderV1([{credentialRef,providerReference:locator,providerReferenceDigest:referenceDigest(locator)}],{async resolve(_input,collector){collector.submit(result.value);}});
  await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(locator),invocationId:`invocation:native-proxy:${mode}`}),/Proxy result rejected/);assert.equal(result.trapCount(),0);material.fill(0);
}});

test("CR8Q destination-native collector misuse wipes and releases the first accepted material",async()=>{const locator="native://publishing/collector-misuse";for(const mode of ["double","throw_after"] as const){let releases=0;const material=new TextEncoder().encode(`native-collector-${mode}`),provider=new DestinationNativeSecretProviderV1([{credentialRef,providerReference:locator,providerReferenceDigest:referenceDigest(locator)}],{async resolve(_input,collector){collector.submit({status:"resolved",material,release:async()=>{releases+=1;}});if(mode==="double")collector.submit({status:"unavailable",safeCode:"missing"});else throw new Error("after submit");}});await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(locator),invocationId:`invocation:native-collector:${mode}`}),/collector conflict|after submit/);assert.ok(material.every((byte)=>byte===0));assert.equal(releases,1);}});

test("CR8Q destination-native binary validation rejects behavior and shared backing before handoff",async()=>{const locator="native://publishing/binary-boundary";for(const mode of ["shared","buffer_getter","buffer_data","byte_length_getter","byte_length_data","subclass","prototype_drift","detached","backing_constructor_getter","method_getters","subview_offset","subview_prefix"] as BinaryViewAttackMode[]){let releases=0;const binary=binaryViewAttack(mode),provider=new DestinationNativeSecretProviderV1([{credentialRef,providerReference:locator,providerReferenceDigest:referenceDigest(locator)}],{async resolve(_input,collector){collector.submit({status:"resolved",material:binary.value,release:async()=>{releases+=1;}});}});await assert.rejects(acquire(provider,{credentialRef,providerReferenceDigest:referenceDigest(locator),invocationId:`invocation:native-binary:${mode}`}),/provider result invalid/);assert.equal(binary.getterCount(),0);assert.equal(binary.isWiped(),true);assert.equal(releases,1);}});
