import assert from "node:assert/strict";
import test from "node:test";
import {chmod,copyFile,mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {DatabaseSync} from "node:sqlite";
import {InMemoryRollbackCheckpointStoreV1,sha256Digest} from "../src/security";
import {NODE_POLICY_CONTRACT_V1,computeNormalizedOperationDigest,type LocalPolicyDecisionV1,type NormalizedLocalPolicyRequestV1} from "../src/node-policy/v1";
import {buildCredentialCatalogEntryV1,buildSecretInvocationGrantV1,NodeLocalSecretBrokerV1,SafeCredentialCatalogV1,SECRET_BROKER_CONTRACT_V1,SyntheticSecretProviderV1,
  BitwardenSecretProviderV1,FixedConsumerSecretBrokerV1,SqliteSecretInvocationLedgerV1,type CredentialCatalogEntryV1,type NodeLocalSecretProviderV1,type ProviderCommandPlanV1,type SecretInvocationGrantV1} from "../src/secret-broker/v1";
import {binaryViewAttack,observedProxy,type BinaryViewAttackMode,type ObservedProxyMode} from "./proxy-test-helper";

const t0="2026-08-28T19:00:00.000Z",t30="2026-08-28T19:00:30.000Z";const digest=(label:string)=>sha256Digest({label});
const credentialRef="credential:publishing",tenantId="tenant:control-room",nodeId="node:mac",projectId="project:content",executorId="executor:publisher",operationId="publish:draft",purposeId="purpose:publish";

function request(overrides:Partial<NormalizedLocalPolicyRequestV1>={}):NormalizedLocalPolicyRequestV1{const base:NormalizedLocalPolicyRequestV1={contractVersion:NODE_POLICY_CONTRACT_V1,requestId:"request:credential",tenantId,nodeId,nodeClass:"node-class:mac",projectId,jobId:"job:publish",attemptId:"attempt:one",leaseId:"lease:one",leaseEpoch:1,
  executorId,operationId,operationDigest:digest("placeholder"),authorityDigest:digest("authority"),credentialRefs:[credentialRef],target:{kind:"none"},risk:"medium",externalEffect:false,estimatedDurationSeconds:30,occurredAt:t0};
  const value={...base,...overrides};return overrides.operationDigest?value:{...value,operationDigest:computeNormalizedOperationDigest(value)};}
function decision(value=request(),accepted=true):LocalPolicyDecisionV1{return accepted?{contractVersion:NODE_POLICY_CONTRACT_V1,requestId:value.requestId,requestDigest:sha256Digest(value),ceilingDigest:digest("ceiling"),authorityDigest:value.authorityDigest,decidedAt:t0,accepted:true}:
  {contractVersion:NODE_POLICY_CONTRACT_V1,requestId:value.requestId,requestDigest:sha256Digest(value),ceilingDigest:digest("ceiling"),authorityDigest:value.authorityDigest,decidedAt:t0,accepted:false,detail:"credential_not_allowed",wireCategory:"policy"};}
function entry(overrides:Partial<CredentialCatalogEntryV1>={}):CredentialCatalogEntryV1{return buildCredentialCatalogEntryV1({contractVersion:SECRET_BROKER_CONTRACT_V1,credentialRef,tenantId,nodeId,revision:1,projectIds:[projectId],executorIds:[executorId],operationIds:[operationId],purposeIds:[purposeId],providerKind:"synthetic_test",providerReferenceDigest:digest("provider-reference"),materialKind:"api_token",state:"active",maxLeaseSeconds:60,singleUseOnly:true,createdAt:t0,rotatedAt:t0,...overrides});}
function grant(item=entry(),req=request(),overrides:Partial<{credentialRef:string;purposeId:string;invocationId:string;nonce:string;expiresAt:string}>={}):SecretInvocationGrantV1{return buildSecretInvocationGrantV1({request:req,decision:decision(req),entry:item,credentialRef, purposeId,invocationId:"credential-invocation:one",nonce:"synthetic-nonce-00000001",expiresAt:t30,...overrides});}
function authorize(broker:NodeLocalSecretBrokerV1,req=request(),overrides:Partial<{credentialRef:string;purposeId:string;invocationId:string;nonce:string;expiresAt:string}>={}):SecretInvocationGrantV1{return broker.authorize({request:req,decision:decision(req),credentialRef,purposeId,invocationId:"credential-invocation:one",nonce:"synthetic-nonce-00000001",expiresAt:t30,...overrides});}
function setup(){const catalog=new SafeCredentialCatalogV1();const item=entry();catalog.register(item);const canary=new TextEncoder().encode("canary-local-credential-material-001");const provider=new SyntheticSecretProviderV1([{credentialRef,providerReferenceDigest:item.providerReferenceDigest,material:canary}]);return{catalog,item,provider,broker:new NodeLocalSecretBrokerV1(catalog,[provider]),canaryText:new TextDecoder().decode(canary)};}

test("CR8E catalog contains safe reference metadata only and is exact-replay safe",()=>{const catalog=new SafeCredentialCatalogV1(),item=entry();assert.equal(catalog.register(item).replayed,false);assert.equal(catalog.register(item).replayed,true);
  assert.throws(()=>catalog.register({...item,providerReferenceDigest:digest("drift")}),/catalog integrity|catalog conflict/);assert.throws(()=>catalog.register({...item,rawProviderLocator:"vault/item/field"}),/unrecognized/i);
  assert.doesNotMatch(JSON.stringify(catalog.safeSnapshot()),/vault\/item|canary-local|password=/i);
});

test("CR8E catalog replacement is monotonic and can revoke without carrying material",()=>{const catalog=new SafeCredentialCatalogV1(),original=entry();catalog.register(original);const revoked=entry({revision:2,state:"revoked",rotatedAt:"2026-08-28T19:01:00.000Z",providerReferenceDigest:digest("revoked-reference")});
  assert.equal(catalog.replace({expectedEntryDigest:original.entryDigest,entry:revoked}).state,"revoked");assert.throws(()=>catalog.replace({expectedEntryDigest:original.entryDigest,entry:entry({revision:3})}),/catalog conflict/);
});

test("CR8Q catalog stores and returns deeply isolated frozen authority metadata",()=>{const catalog=new SafeCredentialCatalogV1(),original=entry(),registered=catalog.register(original).entry;original.projectIds.push("project:other");
  assert.throws(()=>registered.projectIds.push("project:other"),TypeError);assert.throws(()=>{registered.maxLeaseSeconds=999;},TypeError);
  const replay=catalog.register(entry()).entry,resolved=catalog.resolve(credentialRef)!,snapshot=catalog.safeSnapshot()[0];for(const value of [replay,resolved,snapshot])assert.throws(()=>value.executorIds.push("executor:other"),TypeError);
  assert.deepEqual(catalog.resolve(credentialRef)?.projectIds,[projectId]);const outside=request({projectId:"project:other"}),broker=new NodeLocalSecretBrokerV1(catalog,[new SyntheticSecretProviderV1([])]);
  assert.throws(()=>authorize(broker,outside,{invocationId:"credential-invocation:mutated-catalog"}),/scope denied/);
  const replacement=entry({revision:2,rotatedAt:"2026-08-28T19:01:00.000Z",projectIds:[projectId,"project:second"]}),returned=catalog.replace({expectedEntryDigest:registered.entryDigest,entry:replacement});
  assert.throws(()=>returned.projectIds.push("project:third"),TypeError);replacement.projectIds.push("project:third");assert.deepEqual(catalog.resolve(credentialRef)?.projectIds,[projectId,"project:second"]);
});

test("CR8E grant derives only from accepted exact local admission and bounded catalog scope",()=>{const item=entry(),req=request(),valid=grant(item,req);assert.equal(valid.singleUse,true);assert.notEqual(valid.nonceDigest,"synthetic-nonce-00000001");
  assert.throws(()=>buildSecretInvocationGrantV1({request:req,decision:decision(req,false),entry:item,credentialRef,purposeId,invocationId:"credential-invocation:denied",nonce:"synthetic-nonce-00000002",expiresAt:t30}),/accepted local admission/);
  assert.throws(()=>grant(item,req,{purposeId:"purpose:other"}),/scope denied/);assert.throws(()=>grant(item,req,{expiresAt:"2026-08-28T19:02:00.000Z"}),/lease invalid/);
  const drift=request({operationDigest:digest("forged-operation")});assert.throws(()=>buildSecretInvocationGrantV1({request:drift,decision:decision(drift),entry:item,credentialRef,purposeId,invocationId:"credential-invocation:drift",nonce:"synthetic-nonce-00000003",expiresAt:t30}),/lease invalid/);
});

test("CR8E successful invocation exposes material only to the local consumer and zeroes its buffer",async()=>{const{broker,provider,canaryText}=setup();let observed="",held:Uint8Array|undefined;const receipt=await broker.invoke({grant:authorize(broker),now:t0,consumer:{async consume(material,_context,result){held=material;observed=new TextDecoder().decode(material);result.submit({outcome:"succeeded",outputDigest:digest("published")});}}});
  assert.equal(observed,canaryText);assert.ok(held?.every((byte)=>byte===0));assert.equal(receipt.state,"succeeded");assert.deepEqual(provider.safeMetrics(),{acquires:1,releases:1});assert.doesNotMatch(JSON.stringify({receipt,ledger:broker.safeLedger()}),new RegExp(canaryText));assert.equal(receipt.grantsExecutionAuthority,false);
});

test("CR8E exact invocation replay returns one receipt without reacquiring material",async()=>{const{broker,provider}=setup();const item=authorize(broker);const consumer={async consume(_material:Uint8Array,_context:unknown,result:{submit(value:unknown):void}){result.submit({outcome:"succeeded" as const,outputDigest:digest("done")});}};const first=await broker.invoke({grant:item,now:t0,consumer});const replay=await broker.invoke({grant:item,now:t0,consumer});assert.deepEqual(replay,first);assert.deepEqual(provider.safeMetrics(),{acquires:1,releases:1});
  await assert.rejects(broker.invoke({grant:{...item,nonceDigest:digest("drift")},now:t0,consumer}),/grant integrity|replay conflict/);
});

test("CR8E terminal replay is immutable and remains available after grant expiry and catalog revocation",async()=>{const current=setup(),value=authorize(current.broker),consumer={async consume(_material:Uint8Array,_context:unknown,result:{submit(value:unknown):void}){result.submit({outcome:"succeeded" as const,outputDigest:digest("terminal")});}};
  const first=await current.broker.invoke({grant:value,now:t0,consumer}),expected=structuredClone(first);first.safeCode="caller_mutation";
  current.catalog.replace({expectedEntryDigest:current.item.entryDigest,entry:entry({revision:2,state:"revoked",rotatedAt:"2026-08-28T19:00:01.000Z"})});
  assert.deepEqual(await current.broker.invoke({grant:value,now:t30,consumer:{async consume(){throw new Error("must not reacquire");}}}),expected);assert.equal(current.provider.safeMetrics().acquires,1);
});

test("CR8E concurrent duplicate cannot consume one invocation twice",async()=>{const{broker,provider}=setup();let release!:()=>void;const gate=new Promise<void>((resolve)=>{release=resolve;});const item=authorize(broker);const first=broker.invoke({grant:item,now:t0,consumer:{async consume(_material,_context,result){await gate;result.submit({outcome:"succeeded",outputDigest:digest("done")});}}});
  await assert.rejects(broker.invoke({grant:item,now:t0,consumer:{async consume(){throw new Error("must not run");}}}),/in progress/);release();assert.equal((await first).state,"succeeded");assert.equal(provider.safeMetrics().acquires,1);
});

test("CR8E definite provider unavailability is terminal and exact replay does not resolve again",async()=>{const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);let calls=0;const provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,result){calls++;result.submit({status:"unavailable",safeCode:"locked"});}};const broker=new NodeLocalSecretBrokerV1(catalog,[provider]);const value=authorize(broker);const consumer={async consume(){throw new Error("must not run");}};
  assert.equal((await broker.invoke({grant:value,now:t0,consumer})).safeCode,"provider_locked");assert.equal((await broker.invoke({grant:value,now:t0,consumer})).state,"failed");assert.equal(calls,1);
});

test("CR8E provider, consumer, and cleanup uncertainty become terminal ambiguity",async()=>{const base=entry();for(const mode of ["provider","consumer","cleanup"] as const){const catalog=new SafeCredentialCatalogV1();catalog.register(base);let material:Uint8Array|undefined;const provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,result){if(mode==="provider")throw new Error("unknown");material=new TextEncoder().encode("canary-local-credential-material-002");result.submit({status:"resolved",material,release:async()=>{if(mode==="cleanup")throw new Error("unknown");}});}};
    const broker=new NodeLocalSecretBrokerV1(catalog,[provider]),value=authorize(broker,request(),{invocationId:`credential-invocation:${mode}`});const receipt=await broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,result){if(mode==="consumer")throw new Error("unknown");result.submit({outcome:"succeeded",outputDigest:digest("done")});}}});assert.equal(receipt.state,"ambiguous");if(material)assert.ok(material.every((byte)=>byte===0));
    const replay=await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not retry");}}});assert.deepEqual(replay,receipt);
  }});

test("CR8E malformed provider envelopes are wiped and become terminal ambiguity",async()=>{const item=entry(),catalog=new SafeCredentialCatalogV1();catalog.register(item);const material=new TextEncoder().encode("canary-malformed-provider-envelope"),provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,result){result.submit({status:"unavailable",safeCode:"locked",material});}},broker=new NodeLocalSecretBrokerV1(catalog,[provider]),value=authorize(broker);const receipt=await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not run");}}});assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,"provider_result_invalid");assert.ok(material.every((byte)=>byte===0));assert.deepEqual(await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not run");}}}),receipt);
});

test("CR8E malformed or material-bearing consumer output fails closed without leakage",async()=>{const{broker,canaryText}=setup();const receipt=await broker.invoke({grant:authorize(broker),now:t0,consumer:{async consume(_material,_context,result){result.submit({outcome:"succeeded",outputDigest:digest("done"),material:canaryText});}}});assert.equal(receipt.state,"ambiguous");assert.doesNotMatch(JSON.stringify(receipt),new RegExp(canaryText));});

test("CR8Q consumer results require exact ordinary data without executing getters",async()=>{for(const outcome of ["succeeded","definite_failure","ambiguous"] as const){for(const shape of ["accessor_outcome","accessor_value","inherited","symbol","non_enumerable","enumerable_extra"] as const){const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);let acquires=0,releases=0,consumerCalls=0,getterCalls=0;const secretText=`canary-consumer-shape-${outcome}-${shape}`,material=new TextEncoder().encode(secretText),provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,result){acquires++;result.submit({status:"resolved",material,release:async()=>{releases++;}});}};
    const broker=new NodeLocalSecretBrokerV1(catalog,[provider]),value=authorize(broker,request(),{invocationId:`credential-invocation:${outcome}:${shape}`,nonce:`synthetic-nonce-${outcome}-${shape}`}),ordinary=outcome==="succeeded"?{outcome,outputDigest:digest(`${outcome}-${shape}`)}:{outcome,safeCode:`consumer_${outcome}`};let malformed:object;
    if(shape==="accessor_outcome"){malformed={...ordinary};Object.defineProperty(malformed,"outcome",{enumerable:true,configurable:true,get(){getterCalls++;return outcome;}});}
    else if(shape==="accessor_value"){malformed={...ordinary};const key=outcome==="succeeded"?"outputDigest":"safeCode",value=Object.getOwnPropertyDescriptor(ordinary,key)?.value;Object.defineProperty(malformed,key,{enumerable:true,configurable:true,get(){getterCalls++;return value;}});}
    else if(shape==="inherited")malformed=Object.create(ordinary) as object;
    else if(shape==="symbol")malformed={...ordinary,[Symbol("hidden")]:secretText};
    else if(shape==="non_enumerable"){malformed={...ordinary};Object.defineProperty(malformed,"hiddenMaterial",{enumerable:false,value:secretText});}
    else malformed={...ordinary,material:secretText};
    const receipt=await broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,result){consumerCalls++;result.submit(malformed);}}});assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,"consumer_or_cleanup_outcome_unknown");assert.equal(getterCalls,0);assert.equal(acquires,1);assert.equal(releases,1);assert.equal(consumerCalls,1);assert.ok(material.every((byte)=>byte===0));assert.doesNotMatch(JSON.stringify({receipt,ledger:broker.safeLedger()}),new RegExp(secretText));
    assert.deepEqual(await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not replay consumer");}}}),receipt);assert.equal(acquires,1);assert.equal(releases,1);assert.equal(consumerCalls,1);
  }}});

test("CR8Q exact ordinary consumer results preserve all three terminal outcomes",async()=>{for(const outcome of ["succeeded","definite_failure","ambiguous"] as const){const current=setup(),value=authorize(current.broker,request(),{invocationId:`credential-invocation:ordinary:${outcome}`,nonce:`synthetic-nonce-ordinary-${outcome}`}),result=outcome==="succeeded"?{outcome,outputDigest:digest(`ordinary-${outcome}`)}:{outcome,safeCode:`consumer_${outcome}`};const receipt=await current.broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,collector){collector.submit(result);}}});assert.equal(receipt.state,outcome==="succeeded"?"succeeded":outcome==="definite_failure"?"failed":"ambiguous");assert.equal(receipt.safeCode,outcome==="succeeded"?"completed":`consumer_${outcome}`);}});

test("CR8Q Proxy consumer results execute zero traps, clean up once, and replay without reacquisition",async()=>{for(const mode of ["transparent","key_hiding","descriptor_fabricating","throwing"] as ObservedProxyMode[]){const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);let acquires=0,releases=0,consumerCalls=0;const material=new TextEncoder().encode(`proxy-consumer-material-${mode}`),provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,result){acquires+=1;result.submit({status:"resolved",material,release:async()=>{releases+=1;}});}};
  const target={outcome:"succeeded",outputDigest:digest(`proxy-consumer-${mode}`),...(mode==="key_hiding"?{[Symbol("hidden")]:"widening"}:{})},proxy=observedProxy(target,mode),broker=new NodeLocalSecretBrokerV1(catalog,[provider]),value=authorize(broker,request(),{invocationId:`credential-invocation:proxy-consumer:${mode}`,nonce:`synthetic-nonce-proxy-consumer-${mode}`});
  const receipt=await broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,result){consumerCalls+=1;result.submit(proxy.value);}}});assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,"consumer_or_cleanup_outcome_unknown");assert.equal(proxy.trapCount(),0);assert.equal(acquires,1);assert.equal(releases,1);assert.equal(consumerCalls,1);assert.ok(material.every((byte)=>byte===0));
  assert.deepEqual(await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not replay");}}}),receipt);assert.equal(acquires,1);assert.equal(releases,1);assert.equal(consumerCalls,1);
}});

test("CR8Q Proxy provider envelopes and provider wiring execute zero traps and fail closed",async()=>{for(const mode of ["transparent","key_hiding","descriptor_fabricating","throwing"] as ObservedProxyMode[]){const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);let acquires=0,consumerCalls=0;const material=new TextEncoder().encode(`proxy-provider-material-${mode}`),target={status:"resolved" as const,material,release:async()=>undefined,...(mode==="key_hiding"?{[Symbol("hidden")]:true}:{})},result=observedProxy(target,mode),provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,collector){acquires+=1;collector.submit(result.value);}};
  const broker=new NodeLocalSecretBrokerV1(catalog,[provider]),value=authorize(broker,request(),{invocationId:`credential-invocation:proxy-provider:${mode}`,nonce:`synthetic-nonce-proxy-provider-${mode}`}),receipt=await broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,collector){consumerCalls+=1;collector.submit({outcome:"succeeded",outputDigest:digest("must-not-run")});}}});
  assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,"provider_outcome_unknown");assert.equal(result.trapCount(),0);assert.equal(acquires,1);assert.equal(consumerCalls,0);assert.deepEqual(await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not replay");}}}),receipt);assert.equal(acquires,1);material.fill(0);
}
  const providerTarget:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,result){result.submit({status:"unavailable",safeCode:"missing"});}},providerProxy=observedProxy(providerTarget,"throwing");assert.throws(()=>new NodeLocalSecretBrokerV1(new SafeCredentialCatalogV1(),[providerProxy.value]),/provider invalid/);assert.equal(providerProxy.trapCount(),0);
  const arrayProxy=observedProxy([providerTarget],"throwing");assert.throws(()=>new NodeLocalSecretBrokerV1(new SafeCredentialCatalogV1(),arrayProxy.value),/providers invalid/);assert.equal(arrayProxy.trapCount(),0);
});

test("CR8Q collector misuse is terminal, cleans accepted material, and cannot recover after Proxy rejection",async()=>{for(const mode of ["provider_missing","provider_double","provider_throw_after","provider_proxy_then_ordinary","consumer_missing","consumer_double","consumer_throw_after"] as const){const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);let releases=0,consumerCalls=0;const material=new TextEncoder().encode(`collector-misuse-${mode}`),proxy=observedProxy({status:"resolved" as const,material,release:async()=>{releases+=1;}},"transparent"),provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,collector){if(mode==="provider_missing")return;if(mode==="provider_proxy_then_ordinary"){assert.throws(()=>collector.submit(proxy.value),/Proxy result rejected/);assert.throws(()=>collector.submit({status:"resolved",material,release:async()=>{releases+=1;}}),/collector conflict/);return;}collector.submit({status:"resolved",material,release:async()=>{releases+=1;}});if(mode==="provider_double")collector.submit({status:"unavailable",safeCode:"missing"});if(mode==="provider_throw_after")throw new Error("after submit");}};
  const broker=new NodeLocalSecretBrokerV1(catalog,[provider]),value=authorize(broker,request(),{invocationId:`credential-invocation:collector:${mode}`,nonce:`synthetic-nonce-collector-${mode}`}),receipt=await broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,collector){consumerCalls+=1;if(mode==="consumer_missing")return;collector.submit({outcome:"succeeded",outputDigest:digest(`collector-${mode}`)});if(mode==="consumer_double")collector.submit({outcome:"ambiguous",safeCode:"duplicate"});if(mode==="consumer_throw_after")throw new Error("after submit");}}});assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,mode.startsWith("provider_")?"provider_outcome_unknown":"consumer_or_cleanup_outcome_unknown");assert.equal(proxy.trapCount(),0);assert.equal(consumerCalls,mode.startsWith("provider_")?0:1);assert.equal(releases,["provider_double","provider_throw_after","consumer_missing","consumer_double","consumer_throw_after"].includes(mode)?1:0);if(releases===1)assert.ok(material.every((byte)=>byte===0));else material.fill(0);
  assert.deepEqual(await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not replay");}}}),receipt);
}});

test("CR8Q late provider and consumer submissions cannot change terminal truth",async()=>{let lateProvider:{submit(value:unknown):void}|undefined;const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);const provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,collector){lateProvider=collector;}},broker=new NodeLocalSecretBrokerV1(catalog,[provider]),providerGrant=authorize(broker,request(),{invocationId:"credential-invocation:late-provider",nonce:"synthetic-nonce-late-provider"}),providerReceipt=await broker.invoke({grant:providerGrant,now:t0,consumer:{async consume(){throw new Error("must not run");}}});assert.equal(providerReceipt.safeCode,"provider_outcome_unknown");assert.throws(()=>lateProvider?.submit({status:"unavailable",safeCode:"missing"}),/collector conflict/);assert.deepEqual(await broker.invoke({grant:providerGrant,now:t0,consumer:{async consume(){throw new Error("must not replay");}}}),providerReceipt);
  const current=setup(),consumerGrant=authorize(current.broker,request(),{invocationId:"credential-invocation:late-consumer",nonce:"synthetic-nonce-late-consumer"});let lateConsumer:{submit(value:unknown):void}|undefined;const consumerReceipt=await current.broker.invoke({grant:consumerGrant,now:t0,consumer:{async consume(_material,_context,collector){lateConsumer=collector;collector.submit({outcome:"succeeded",outputDigest:digest("late-consumer")});}}});assert.equal(consumerReceipt.state,"succeeded");assert.throws(()=>lateConsumer?.submit({outcome:"ambiguous",safeCode:"late"}),/collector conflict/);assert.deepEqual(await current.broker.invoke({grant:consumerGrant,now:t0,consumer:{async consume(){throw new Error("must not replay");}}}),consumerReceipt);assert.deepEqual(current.provider.safeMetrics(),{acquires:1,releases:1});
});

test("CR8Q broker rejects widened provider binary views without behavior or consumer exposure",async()=>{for(const mode of ["shared","buffer_getter","buffer_data","byte_length_getter","byte_length_data","subclass","prototype_drift","detached","backing_constructor_getter","method_getters","subview_offset","subview_prefix"] as BinaryViewAttackMode[]){const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);let releases=0,consumerCalls=0;const binary=binaryViewAttack(mode),provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,collector){collector.submit({status:"resolved",material:binary.value,release:async()=>{releases+=1;}});}},broker=new NodeLocalSecretBrokerV1(catalog,[provider]),value=authorize(broker,request(),{invocationId:`credential-invocation:binary:${mode}`,nonce:`synthetic-nonce-binary-${mode}`}),receipt=await broker.invoke({grant:value,now:t0,consumer:{async consume(){consumerCalls+=1;}}});assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,"provider_result_invalid");assert.equal(binary.getterCount(),0);assert.equal(binary.isWiped(),true);assert.equal(releases,1);assert.equal(consumerCalls,0);assert.deepEqual(await broker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not replay");}}}),receipt);}});

test("CR8E expired grants and revoked catalog entries fail before provider resolution",async()=>{const{broker,provider}=setup();await assert.rejects(broker.invoke({grant:authorize(broker),now:t30,consumer:{async consume(){throw new Error("must not run");}}}),/expired/);assert.equal(provider.safeMetrics().acquires,0);
  const catalog=new SafeCredentialCatalogV1(),original=entry();catalog.register(original);const other=new SyntheticSecretProviderV1([]),revokedBroker=new NodeLocalSecretBrokerV1(catalog,[other]),value=authorize(revokedBroker);catalog.replace({expectedEntryDigest:original.entryDigest,entry:entry({revision:2,state:"revoked",rotatedAt:"2026-08-28T19:00:01.000Z"})});await assert.rejects(revokedBroker.invoke({grant:value,now:t0,consumer:{async consume(){throw new Error("must not run");}}}),/unavailable/);assert.equal(other.safeMetrics().acquires,0);
});

test("CR8E a caller-computed grant is not authority until the local broker issues it",async()=>{const{broker,provider}=setup();await assert.rejects(broker.invoke({grant:grant(),now:t0,consumer:{async consume(){throw new Error("must not run");}}}),/not authorized by local broker/);assert.equal(provider.safeMetrics().acquires,0);});

test("CR8E fixed-consumer seam prevents callers from injecting credential-handling code",async()=>{const first=setup(),value=authorize(first.broker),fixed=new FixedConsumerSecretBrokerV1(first.broker,[{executorId,operationId,purposeId,consumer:{async consume(_material,_context,result){result.submit({outcome:"succeeded",outputDigest:digest("fixed-consumer")});}}}]);assert.equal((await fixed.invoke({grant:value,now:t0})).state,"succeeded");
  const second=setup(),denied=authorize(second.broker),noRoute=new FixedConsumerSecretBrokerV1(second.broker,[{executorId:"executor:other",operationId,purposeId,consumer:{async consume(){throw new Error("must not run");}}}]);assert.throws(()=>noRoute.invoke({grant:denied,now:t0}),/route denied/);assert.equal(second.provider.safeMetrics().acquires,0);
});

test("CR8Q fixed-consumer composition rejects Proxy results and wiring before any trap",async()=>{const current=setup(),value=authorize(current.broker,request(),{invocationId:"credential-invocation:fixed-proxy",nonce:"synthetic-nonce-fixed-proxy"}),result=observedProxy({outcome:"succeeded",outputDigest:digest("fixed-proxy"),[Symbol("hidden")]:true},"key_hiding"),fixed=new FixedConsumerSecretBrokerV1(current.broker,[{executorId,operationId,purposeId,consumer:{async consume(_material,_context,collector){collector.submit(result.value);}}}]);
  const receipt=await fixed.invoke({grant:value,now:t0});assert.equal(receipt.state,"ambiguous");assert.equal(result.trapCount(),0);assert.deepEqual(current.provider.safeMetrics(),{acquires:1,releases:1});
  const consumer=observedProxy({async consume(_material:Uint8Array,_context:unknown,collector:{submit(value:unknown):void}){collector.submit({outcome:"succeeded" as const,outputDigest:digest("blocked")});}},"throwing");assert.throws(()=>new FixedConsumerSecretBrokerV1(current.broker,[{executorId,operationId,purposeId,consumer:consumer.value}]),/route invalid/);assert.equal(consumer.trapCount(),0);
  const routeArray=observedProxy([{executorId,operationId,purposeId,consumer:{async consume(_material:Uint8Array,_context:unknown,collector:{submit(value:unknown):void}){collector.submit({outcome:"succeeded" as const,outputDigest:digest("blocked-array")});}}}],"throwing");assert.throws(()=>new FixedConsumerSecretBrokerV1(current.broker,routeArray.value),/routes invalid/);assert.equal(routeArray.trapCount(),0);
});

test("CR8E construction captures fixed provider and consumer functions against later mutation",async()=>{const catalog=new SafeCredentialCatalogV1(),item=entry();catalog.register(item);let releases=0;
  const provider:NodeLocalSecretProviderV1={providerKind:"synthetic_test",async acquire(_input,result){result.submit({status:"resolved",material:new TextEncoder().encode("canary-captured-provider-material"),release:async()=>{releases++;}});}};
  const broker=new NodeLocalSecretBrokerV1(catalog,[provider]);provider.acquire=async()=>{throw new Error("mutated provider must not run");};
  const consumer={async consume(_material:Uint8Array,_context:unknown,result:{submit(value:unknown):void}){result.submit({outcome:"succeeded" as const,outputDigest:digest("captured-consumer")});}};const fixed=new FixedConsumerSecretBrokerV1(broker,[{executorId,operationId,purposeId,consumer}]);
  consumer.consume=async()=>{throw new Error("mutated consumer must not run");};assert.equal((await fixed.invoke({grant:authorize(broker),now:t0})).state,"succeeded");assert.equal(releases,1);
});

test("CR8E expiry or broker-clock rollback after material use becomes terminal ambiguity",async()=>{for(const mode of ["expired","rollback"] as const){const current=setup(),observations=mode==="expired"?[t0,t30]:[t0,"2026-08-28T18:59:59.000Z"];let index=0;const broker=new NodeLocalSecretBrokerV1(current.catalog,[current.provider],undefined,{clock:()=>observations[Math.min(index++,observations.length-1)]});const value=authorize(broker,request(),{invocationId:`credential-invocation:${mode}`});const receipt=await broker.invoke({grant:value,now:"2020-01-01T00:00:00.000Z",consumer:{async consume(_material,_context,result){result.submit({outcome:"succeeded",outputDigest:digest(mode)});}}});assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,"consumer_or_cleanup_outcome_unknown");assert.equal(current.provider.safeMetrics().acquires,1);
  }});

test("CR8E live provider construction is unavailable in the effect-free core",()=>{const catalog=new SafeCredentialCatalogV1();const live:NodeLocalSecretProviderV1={providerKind:"bitwarden",async acquire(){throw new Error("must not run");}};assert.throws(()=>new NodeLocalSecretBrokerV1(catalog,[live]),/live credential providers are disabled/);});

test("CR8E durable ledger preserves terminal replay across restart without reacquiring",async()=>{const directory=await mkdtemp(join(tmpdir(),"cr8e-ledger-success-"));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),key=new Uint8Array(32).fill(0x61),identity=digest("credential-ledger"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true});try{const first=setup(),ledger1=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create",testOnlyAllowEphemeral:true,clock:()=>t0}),broker1=new NodeLocalSecretBrokerV1(first.catalog,[first.provider],ledger1),value=authorize(broker1);
    const receipt=await broker1.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,result){result.submit({outcome:"succeeded",outputDigest:digest("durable-output")});}}});ledger1.close();
    const second=setup(),ledger2=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open",testOnlyAllowEphemeral:true,clock:()=>"2026-08-28T19:00:05.000Z"}),broker2=new NodeLocalSecretBrokerV1(second.catalog,[second.provider],ledger2);assert.equal(authorize(broker2).grantDigest,value.grantDigest);
    assert.deepEqual(await broker2.invoke({grant:value,now:"2026-08-28T19:00:05.000Z",consumer:{async consume(){throw new Error("must not reacquire");}}}),receipt);assert.equal(second.provider.safeMetrics().acquires,0);ledger2.close();
    assert.doesNotMatch((await readFile(path)).toString("utf8"),/canary-local-credential-material/);
  }finally{await rm(directory,{recursive:true,force:true});}});

test("CR8E durable ledger converts every claimed invocation to terminal ambiguity on restart",async()=>{const directory=await mkdtemp(join(tmpdir(),"cr8e-ledger-crash-"));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),key=new Uint8Array(32).fill(0x62),identity=digest("credential-ledger-crash"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true});try{const first=setup(),ledger1=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create",testOnlyAllowEphemeral:true,clock:()=>t0}),broker1=new NodeLocalSecretBrokerV1(first.catalog,[first.provider],ledger1),value=authorize(broker1);assert.equal(ledger1.claim(value,t0).disposition,"dispatch");ledger1.close();
    const second=setup(),ledger2=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open",testOnlyAllowEphemeral:true,clock:()=>"2026-08-28T19:00:06.000Z"}),broker2=new NodeLocalSecretBrokerV1(second.catalog,[second.provider],ledger2);authorize(broker2);const receipt=await broker2.invoke({grant:value,now:"2026-08-28T19:00:06.000Z",consumer:{async consume(){throw new Error("must not run");}}});assert.equal(receipt.state,"ambiguous");assert.equal(receipt.safeCode,"broker_restarted_outcome_unknown");assert.equal(second.provider.safeMetrics().acquires,0);ledger2.close();
  }finally{await rm(directory,{recursive:true,force:true});}});

test("CR8E durable ledger rejects wrong key, wrong identity, row tampering, deletion, clock tampering, and added schema",async()=>{for(const attack of ["wrong_key","wrong_identity","row","delete","clock","trigger"] as const){const directory=await mkdtemp(join(tmpdir(),`cr8e-ledger-${attack}-`));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),key=new Uint8Array(32).fill(0x63),identity=digest("credential-ledger-tamper"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true});try{const current=setup(),ledger=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create"}),broker=new NodeLocalSecretBrokerV1(current.catalog,[current.provider],ledger);authorize(broker);ledger.close();
      if(attack==="wrong_key"){assert.throws(()=>new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:new Uint8Array(32).fill(0x64),checkpointStore,mode:"open"}),/integrity/);continue;}if(attack==="wrong_identity"){assert.throws(()=>new SqliteSecretInvocationLedgerV1(path,digest("other-ledger"),{integrityKey:key,checkpointStore,mode:"open"}),/identity/);continue;}
      const db=new DatabaseSync(path);if(attack==="row")db.prepare("UPDATE secret_invocation_records SET grant_json='{}' WHERE invocation_id=?").run("credential-invocation:one");if(attack==="delete")db.prepare("DELETE FROM secret_invocation_records").run();if(attack==="clock")db.prepare("UPDATE secret_invocation_metadata SET high_water_at=? WHERE singleton=1").run("2026-08-28T18:00:00.000Z");if(attack==="trigger")db.exec("CREATE TRIGGER hostile AFTER INSERT ON secret_invocation_records BEGIN DELETE FROM secret_invocation_records; END");db.close();assert.throws(()=>new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open"}),/schema|integrity|rollback/);
    }finally{await rm(directory,{recursive:true,force:true});}}});

test("CR8E durable high-water rejects clock rollback across restart",async()=>{const directory=await mkdtemp(join(tmpdir(),"cr8e-ledger-high-water-"));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),key=new Uint8Array(32).fill(0x66),identity=digest("credential-ledger-high-water"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true});try{
    const first=setup(),ledger1=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create",testOnlyAllowEphemeral:true,clock:()=>t0}),broker1=new NodeLocalSecretBrokerV1(first.catalog,[first.provider],ledger1);
    const claimed=authorize(broker1,request(),{invocationId:"credential-invocation:claimed",nonce:"synthetic-nonce-claimed"}),waiting=authorize(broker1,request(),{invocationId:"credential-invocation:waiting",nonce:"synthetic-nonce-waiting"});
    assert.equal(ledger1.claim(claimed,"2026-08-28T19:00:10.000Z").disposition,"dispatch");ledger1.close();
    const ledger2=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open",testOnlyAllowEphemeral:true,clock:()=>"2026-08-28T19:00:05.000Z"});assert.throws(()=>ledger2.claim(waiting,"2026-08-28T19:00:05.000Z"),/clock rollback/);ledger2.close();
  }finally{await rm(directory,{recursive:true,force:true});}});

test("CR8Q durable ledger refuses missing, empty, recreated, and older files",async()=>{const key=new Uint8Array(32).fill(0x67),identity=digest("credential-ledger-file-replacement");
  for(const attack of ["missing","empty","recreated"] as const){const directory=await mkdtemp(join(tmpdir(),`cr8q-ledger-${attack}-`));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true});try{
    const ledger=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create",testOnlyAllowEphemeral:true,clock:()=>t0});const current=setup(),broker=new NodeLocalSecretBrokerV1(current.catalog,[current.provider],ledger),value=authorize(broker);await broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,result){result.submit({outcome:"succeeded",outputDigest:digest("terminal")});}}});ledger.close();await rm(path,{force:true});
    if(attack==="missing")assert.throws(()=>new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open"}),/missing/);
    if(attack==="empty"){await writeFile(path,"",{mode:0o600});assert.throws(()=>new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open"}),/schema/);}
    if(attack==="recreated")assert.throws(()=>new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create"}),/checkpoint/);
  }finally{await rm(directory,{recursive:true,force:true});}}
  const directory=await mkdtemp(join(tmpdir(),"cr8q-ledger-older-"));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),snapshot=join(directory,"ledger-old.sqlite"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true});try{
    const first=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create",testOnlyAllowEphemeral:true,clock:()=>t0});first.close();await copyFile(path,snapshot);
    const second=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open",testOnlyAllowEphemeral:true,clock:()=>t0}),current=setup(),broker=new NodeLocalSecretBrokerV1(current.catalog,[current.provider],second),value=authorize(broker);await broker.invoke({grant:value,now:t0,consumer:{async consume(_material,_context,result){result.submit({outcome:"succeeded",outputDigest:digest("newer-terminal")});}}});second.close();await copyFile(snapshot,path);
    assert.throws(()=>new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"open"}),/rollback/);
  }finally{await rm(directory,{recursive:true,force:true});}
});

test("CR8Q durable ledger captures its trusted checkpoint functions",async()=>{const directory=await mkdtemp(join(tmpdir(),"cr8q-ledger-captured-checkpoint-"));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),key=new Uint8Array(32).fill(0x68),identity=digest("credential-ledger-captured-checkpoint"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true});try{
  const ledger=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create",testOnlyAllowEphemeral:true,clock:()=>t0});checkpointStore.read=()=>undefined;checkpointStore.initialize=()=>{throw new Error("mutated initialize");};checkpointStore.advance=()=>{throw new Error("mutated advance");};
  const current=setup(),broker=new NodeLocalSecretBrokerV1(current.catalog,[current.provider],ledger);assert.equal((await broker.invoke({grant:authorize(broker),now:t0,consumer:{async consume(_material,_context,result){result.submit({outcome:"succeeded",outputDigest:digest("captured-checkpoint")});}}})).state,"succeeded");ledger.close();
}finally{await rm(directory,{recursive:true,force:true});}});

test("CR8E durable fixed-consumer broker composes with the Bitwarden command adapter without persisting material",async()=>{const directory=await mkdtemp(join(tmpdir(),"cr8e-bitwarden-compose-"));await chmod(directory,0o700);const path=join(directory,"ledger.sqlite"),key=new Uint8Array(32).fill(0x65),identity=digest("credential-ledger-bitwarden"),checkpointStore=new InMemoryRollbackCheckpointStoreV1({testOnly:true}),itemId="123e4567-e89b-12d3-a456-426614174000",providerReferenceDigest=sha256Digest({providerReference:itemId}),canary="synthetic-bitwarden-material-never-persist";try{const catalog=new SafeCredentialCatalogV1(),item=entry({providerKind:"bitwarden",providerReferenceDigest});catalog.register(item);const plans:ProviderCommandPlanV1[]=[];const provider=new BitwardenSecretProviderV1({executablePath:"/opt/control-room/bin/bw",expectedBinaryDigest:digest("pinned-bitwarden"),timeoutMilliseconds:5_000,maximumOutputBytes:1_024,bindings:[{credentialRef,providerReference:itemId,providerReferenceDigest}]},{async run(plan,result){plans.push(structuredClone(plan));result.submit({status:"completed",exitCode:0,stdout:new TextEncoder().encode(canary),observedBinaryDigest:digest("pinned-bitwarden"),stderrDigest:digest("empty-stderr")});}});const ledger=new SqliteSecretInvocationLedgerV1(path,identity,{integrityKey:key,checkpointStore,mode:"create",testOnlyAllowEphemeral:true,clock:()=>t0}),broker=new NodeLocalSecretBrokerV1(catalog,[provider],ledger,{allowEffectFreeProviderAdapters:true,clock:()=>t0}),fixed=new FixedConsumerSecretBrokerV1(broker,[{executorId,operationId,purposeId,consumer:{async consume(material,_context,result){assert.equal(new TextDecoder().decode(material),canary);result.submit({outcome:"succeeded",outputDigest:digest("provider-output")});}}}]),value=authorize(broker);assert.equal((await fixed.invoke({grant:value,now:t0})).state,"succeeded");assert.deepEqual(plans[0].args,["get","password",itemId,"--nointeraction"]);assert.doesNotMatch((await readFile(path)).toString("utf8"),new RegExp(canary));ledger.close();
  }finally{await rm(directory,{recursive:true,force:true});}});
