import { DatabaseSync } from "node:sqlite";
import { z } from "zod";
import { consequentialApprovalDecisionSchemaV1, consequentialApprovalRequestSchemaV1, type ConsequentialApprovalDecisionV1, type ConsequentialApprovalRequestV1 } from "../../../completion-gate/v1";
import { hmacSha256Tag, sha256Digest } from "../../../security";
import { exactProjectWorkspaceJsonV1, ProjectWorkspaceContractErrorV1, projectWorkspaceSafeIdSchemaV1, projectWorkspaceTimeSchemaV1 } from "../../../project-workspace/v1";
import {
  buildAbsNewsLiveReadClaimV1, buildAbsNewsLiveReadCleanupReceiptV1, buildAbsNewsLiveReadMarkerV1, buildAbsNewsLiveReadOutcomeV1,
  parseAbsNewsLiveReadAuthorizationV1, parseAbsNewsLiveReadClaimV1, parseAbsNewsLiveReadCleanupReceiptV1, parseAbsNewsLiveReadMarkerV1,
  parseAbsNewsLiveReadOutcomeV1, parseAbsNewsLiveReadRequestV1, transitionAbsNewsLiveReadClaimV1,
  type AbsNewsLiveReadAuthorizationV1, type AbsNewsLiveReadClaimV1, type AbsNewsLiveReadCleanupReceiptV1,
  type AbsNewsLiveReadMarkerV1, type AbsNewsLiveReadOutcomeV1, type AbsNewsLiveReadRequestV1,
} from "./live-read";

const scopeSchema=z.object({tenantId:projectWorkspaceSafeIdSchemaV1,workspaceId:projectWorkspaceSafeIdSchemaV1,projectId:projectWorkspaceSafeIdSchemaV1}).strict();
const registerSchema=z.object({request:z.unknown(),authorization:z.unknown(),approvalRequest:z.unknown(),approvalDecision:z.unknown()}).strict();
type Scope=z.infer<typeof scopeSchema>;
type Kind="request"|"authorization"|"approval_request"|"approval_decision"|"claim"|"marker"|"cleanup"|"outcome";
type Row={kind:Kind;record_id:string;record_digest:string;semantic_key:string;version:number;payload:string;record_auth_tag:string;recorded_at:string};
type Meta={tenant_id:string;workspace_id:string;project_id:string;revision:number;record_count:number;state_digest:string;state_auth_tag:string};
const TABLES=["abs_news_live_read_metadata","abs_news_live_read_records"];

function snapshot<T>(schema:{parse(value:unknown):T},value:unknown):T{try{return schema.parse(exactProjectWorkspaceJsonV1(value));}catch(error){if(error instanceof ProjectWorkspaceContractErrorV1)throw error;throw new ProjectWorkspaceContractErrorV1("invalid_input");}}
function json(value:string):unknown{try{return JSON.parse(value) as unknown;}catch{throw new ProjectWorkspaceContractErrorV1("integrity_failed");}}

export interface AbsNewsLiveReadBundleV1 { request:AbsNewsLiveReadRequestV1;authorization:AbsNewsLiveReadAuthorizationV1;approvalRequest:ConsequentialApprovalRequestV1;approvalDecision:ConsequentialApprovalDecisionV1; }
export type AbsNewsLiveReadClaimResultV1={disposition:"run_permitted";claim:AbsNewsLiveReadClaimV1;created:boolean}|{disposition:"in_progress";claim:AbsNewsLiveReadClaimV1}|{disposition:"replay";claim:AbsNewsLiveReadClaimV1;outcome:AbsNewsLiveReadOutcomeV1;cleanup:AbsNewsLiveReadCleanupReceiptV1};

export class SqliteAbsNewsLiveReadStoreV1 {
  readonly #db:DatabaseSync;readonly #key:Uint8Array;readonly #scope:Scope;#closed=false;
  constructor(path:string,scopeValue:unknown,options:{integrityKey:Uint8Array;mode:"create"|"open"}){this.#scope=snapshot(scopeSchema,scopeValue);try{hmacSha256Tag(options.integrityKey,{purpose:"abs-news-live-read-ledger"});}catch{throw new ProjectWorkspaceContractErrorV1("integrity_failed");}this.#key=new Uint8Array(options.integrityKey);this.#db=new DatabaseSync(path);const version=Number((this.#db.prepare("PRAGMA user_version").get() as {user_version:number}).user_version);if(options.mode==="create"){if(version!==0)throw new ProjectWorkspaceContractErrorV1("integrity_failed");this.createSchema();this.initialize();}else if(version!==1)throw new ProjectWorkspaceContractErrorV1("integrity_failed");this.verifyIntegrity();}
  close():void{if(!this.#closed){this.#key.fill(0);this.#db.close();this.#closed=true;}}

  register(inputValue:unknown):{bundle:AbsNewsLiveReadBundleV1;replayed:boolean}{const input=snapshot(registerSchema,inputValue),request=parseAbsNewsLiveReadRequestV1(input.request),authorization=parseAbsNewsLiveReadAuthorizationV1(input.authorization);let approvalRequest:ConsequentialApprovalRequestV1,approvalDecision:ConsequentialApprovalDecisionV1;try{approvalRequest=consequentialApprovalRequestSchemaV1.parse(input.approvalRequest) as ConsequentialApprovalRequestV1;approvalDecision=consequentialApprovalDecisionSchemaV1.parse(input.approvalDecision) as ConsequentialApprovalDecisionV1;}catch{throw new ProjectWorkspaceContractErrorV1("invalid_input");}this.scope(request);this.scope(authorization);if(authorization.requestDigest!==request.requestDigest||authorization.approvalRequestDigest!==sha256Digest(approvalRequest)||authorization.approvalDecisionDigest!==sha256Digest(approvalDecision)||approvalDecision.requestDigest!==sha256Digest(approvalRequest))throw new ProjectWorkspaceContractErrorV1("replay_drift");this.verifyIntegrity();return this.transaction(()=>{const replayed=[this.immutable("request",request.requestId,request.requestDigest,request.requestDigest,request.requestedAt,request),this.immutable("approval_request",approvalRequest.id,sha256Digest(approvalRequest),request.requestDigest,approvalRequest.requestedAt,approvalRequest),this.immutable("approval_decision",approvalDecision.id,sha256Digest(approvalDecision),request.requestDigest,approvalDecision.decidedAt,approvalDecision),this.immutable("authorization",authorization.authorizationId,authorization.authorizationDigest,request.requestDigest,authorization.authorizedAt,authorization)].every(Boolean);if(!replayed)this.advance();return{bundle:{request,authorization,approvalRequest,approvalDecision},replayed};});}

  loadBundle(requestId:string):AbsNewsLiveReadBundleV1{this.verifyIntegrity();const requestRow=this.current("request",requestId);if(!requestRow)throw new ProjectWorkspaceContractErrorV1("not_found");const request=this.verified(requestRow) as AbsNewsLiveReadRequestV1,authorizationRow=this.bySemantic("authorization",request.requestDigest),approvalRequestRow=this.bySemantic("approval_request",request.requestDigest),approvalDecisionRow=this.bySemantic("approval_decision",request.requestDigest);if(!authorizationRow||!approvalRequestRow||!approvalDecisionRow)throw new ProjectWorkspaceContractErrorV1("integrity_failed");return{request,authorization:this.verified(authorizationRow) as AbsNewsLiveReadAuthorizationV1,approvalRequest:this.verified(approvalRequestRow) as ConsequentialApprovalRequestV1,approvalDecision:this.verified(approvalDecisionRow) as ConsequentialApprovalDecisionV1};}

  claim(input:{request:unknown;authorization:unknown;claimedAt:string}):AbsNewsLiveReadClaimResultV1{const request=parseAbsNewsLiveReadRequestV1(input.request),authorization=parseAbsNewsLiveReadAuthorizationV1(input.authorization);this.scope(request);this.scope(authorization);this.verifyIntegrity();const proposed=buildAbsNewsLiveReadClaimV1({request,authorization,claimedAt:projectWorkspaceTimeSchemaV1.parse(input.claimedAt)});return this.transaction(()=>{const current=this.bySemantic("claim",proposed.requestDigest);if(current){const claim=this.verified(current) as AbsNewsLiveReadClaimV1;if(claim.claimKey!==proposed.claimKey)throw new ProjectWorkspaceContractErrorV1("replay_drift");if(["succeeded","definite_failure","ambiguous"].includes(claim.state)){const outcome=this.bySemantic("outcome",claim.claimKey),cleanup=this.bySemantic("cleanup",claim.claimKey);if(!outcome||!cleanup)throw new ProjectWorkspaceContractErrorV1("integrity_failed");return{disposition:"replay",claim,outcome:this.verified(outcome) as AbsNewsLiveReadOutcomeV1,cleanup:this.verified(cleanup) as AbsNewsLiveReadCleanupReceiptV1};}return{disposition:claim.state==="claimed"?"run_permitted":"in_progress",claim,created:false};}this.insert("claim",proposed.claimId,proposed.claimDigest,proposed.requestDigest,proposed.version,proposed.updatedAt,proposed);this.advance();return{disposition:"run_permitted",claim:proposed,created:true};});}

  mark(claimValue:unknown,markedAtValue:unknown):{claim:AbsNewsLiveReadClaimV1;marker:AbsNewsLiveReadMarkerV1;replayed:boolean}{const claim=parseAbsNewsLiveReadClaimV1(claimValue),markedAt=projectWorkspaceTimeSchemaV1.parse(markedAtValue);this.scope(claim);this.verifyIntegrity();return this.transaction(()=>{const row=this.bySemantic("claim",claim.requestDigest);if(!row)throw new ProjectWorkspaceContractErrorV1("not_found");const current=this.verified(row) as AbsNewsLiveReadClaimV1;if(current.claimKey!==claim.claimKey)throw new ProjectWorkspaceContractErrorV1("replay_drift");if(current.state==="executing"){const markerRow=this.bySemantic("marker",current.claimKey);if(!markerRow)throw new ProjectWorkspaceContractErrorV1("integrity_failed");return{claim:current,marker:this.verified(markerRow) as AbsNewsLiveReadMarkerV1,replayed:true};}if(current.state!=="claimed"||current.claimDigest!==claim.claimDigest)throw new ProjectWorkspaceContractErrorV1("unsupported_action");const marker=buildAbsNewsLiveReadMarkerV1({claim:current,markedAt}),next=transitionAbsNewsLiveReadClaimV1({claim:current,toState:"executing",updatedAt:markedAt,markerDigest:marker.markerDigest});this.insert("marker",marker.markerId,marker.markerDigest,current.claimKey,1,markedAt,marker);this.insert("claim",next.claimId,next.claimDigest,next.requestDigest,next.version,next.updatedAt,next);this.advance();return{claim:next,marker,replayed:false};});}

  settle(input:{claim:unknown;authorization:unknown;disposition:AbsNewsLiveReadOutcomeV1["disposition"];sourceResultDigests:string[];batchDigests:string[];itemCount:number;totalResponseBytes:number;safeReasonCode:AbsNewsLiveReadOutcomeV1["safeReasonCode"];startedAt:string;settledAt:string}):{claim:AbsNewsLiveReadClaimV1;outcome:AbsNewsLiveReadOutcomeV1;cleanup:AbsNewsLiveReadCleanupReceiptV1;replayed:boolean}{const supplied=parseAbsNewsLiveReadClaimV1(input.claim),authorization=parseAbsNewsLiveReadAuthorizationV1(input.authorization);this.scope(supplied);this.verifyIntegrity();return this.transaction(()=>{const row=this.bySemantic("claim",supplied.requestDigest);if(!row)throw new ProjectWorkspaceContractErrorV1("not_found");const current=this.verified(row) as AbsNewsLiveReadClaimV1;if(["succeeded","definite_failure","ambiguous"].includes(current.state)){const outcomeRow=this.bySemantic("outcome",current.claimKey),cleanupRow=this.bySemantic("cleanup",current.claimKey);if(!outcomeRow||!cleanupRow)throw new ProjectWorkspaceContractErrorV1("integrity_failed");return{claim:current,outcome:this.verified(outcomeRow) as AbsNewsLiveReadOutcomeV1,cleanup:this.verified(cleanupRow) as AbsNewsLiveReadCleanupReceiptV1,replayed:true};}if(current.state!=="executing"||current.claimKey!==supplied.claimKey||current.authorizationDigest!==authorization.authorizationDigest)throw new ProjectWorkspaceContractErrorV1("unsupported_action");const cleanup=buildAbsNewsLiveReadCleanupReceiptV1({claimKey:current.claimKey,requestDigest:current.requestDigest,cleanedAt:input.settledAt}),outcome=buildAbsNewsLiveReadOutcomeV1({...input,claim:current,authorization,cleanup}),next=transitionAbsNewsLiveReadClaimV1({claim:current,toState:input.disposition,updatedAt:input.settledAt,outcomeDigest:outcome.outcomeDigest});this.insert("cleanup",cleanup.cleanupId,cleanup.cleanupDigest,current.claimKey,1,cleanup.cleanedAt,cleanup);this.insert("outcome",outcome.outcomeId,outcome.outcomeDigest,current.claimKey,1,outcome.settledAt,outcome);this.insert("claim",next.claimId,next.claimDigest,next.requestDigest,next.version,next.updatedAt,next);this.advance();return{claim:next,outcome,cleanup,replayed:false};});}

  recoverUnsettled(recoveredAtValue:unknown):AbsNewsLiveReadOutcomeV1[]{const recoveredAt=projectWorkspaceTimeSchemaV1.parse(recoveredAtValue);this.verifyIntegrity();const rows=this.currentRows("claim"),outcomes:AbsNewsLiveReadOutcomeV1[]=[];for(const row of rows){const claim=this.verified(row) as AbsNewsLiveReadClaimV1;if(claim.state!=="executing")continue;const authRow=this.bySemantic("authorization",claim.requestDigest);if(!authRow)throw new ProjectWorkspaceContractErrorV1("integrity_failed");outcomes.push(this.settle({claim,authorization:this.verified(authRow),disposition:"ambiguous",sourceResultDigests:[],batchDigests:[],itemCount:0,totalResponseBytes:0,safeReasonCode:"restart_after_marker",startedAt:claim.updatedAt,settledAt:recoveredAt}).outcome);}return outcomes;}

  verifyIntegrity():{revision:number;recordCount:number;stateDigest:string}{this.open();this.schema();const meta=this.meta(),state=this.state(),tag=hmacSha256Tag(this.#key,this.metaMaterial(Number(meta.revision),Number(meta.record_count),meta.state_digest));if(meta.tenant_id!==this.#scope.tenantId||meta.workspace_id!==this.#scope.workspaceId||meta.project_id!==this.#scope.projectId||Number(meta.record_count)!==state.recordCount||meta.state_digest!==state.stateDigest||meta.state_auth_tag!==tag)throw new ProjectWorkspaceContractErrorV1("integrity_failed");return{revision:Number(meta.revision),recordCount:state.recordCount,stateDigest:state.stateDigest};}

  private immutable(kind:Kind,idValue:string,digestValue:string,semantic:string,recordedAt:string,value:unknown):boolean{const current=this.bySemantic(kind,semantic)??this.current(kind,idValue);if(current){if(current.record_id===idValue&&current.record_digest===digestValue){this.verified(current);return true;}throw new ProjectWorkspaceContractErrorV1("replay_drift");}this.insert(kind,idValue,digestValue,semantic,1,recordedAt,value);return false;}
  private insert(kind:Kind,idValue:string,digestValue:string,semantic:string,version:number,recordedAt:string,value:unknown):void{const payload=JSON.stringify(value),tag=hmacSha256Tag(this.#key,{kind,scope:this.#scope,id:idValue,digest:digestValue,semantic,version,payloadDigest:sha256Digest(value),recordedAt});this.#db.prepare("INSERT INTO abs_news_live_read_records VALUES(?,?,?,?,?,?,?,?)").run(kind,idValue,digestValue,semantic,version,payload,tag,recordedAt);}
  private verified(row:Row):unknown{let value:unknown,digestValue:string;if(row.kind==="request"){value=parseAbsNewsLiveReadRequestV1(json(row.payload));digestValue=(value as AbsNewsLiveReadRequestV1).requestDigest;}else if(row.kind==="authorization"){value=parseAbsNewsLiveReadAuthorizationV1(json(row.payload));digestValue=(value as AbsNewsLiveReadAuthorizationV1).authorizationDigest;}else if(row.kind==="approval_request"){value=consequentialApprovalRequestSchemaV1.parse(json(row.payload));digestValue=sha256Digest(value);}else if(row.kind==="approval_decision"){value=consequentialApprovalDecisionSchemaV1.parse(json(row.payload));digestValue=sha256Digest(value);}else if(row.kind==="claim"){value=parseAbsNewsLiveReadClaimV1(json(row.payload));digestValue=(value as AbsNewsLiveReadClaimV1).claimDigest;}else if(row.kind==="marker"){value=parseAbsNewsLiveReadMarkerV1(json(row.payload));digestValue=(value as AbsNewsLiveReadMarkerV1).markerDigest;}else if(row.kind==="cleanup"){value=parseAbsNewsLiveReadCleanupReceiptV1(json(row.payload));digestValue=(value as AbsNewsLiveReadCleanupReceiptV1).cleanupDigest;}else{value=parseAbsNewsLiveReadOutcomeV1(json(row.payload));digestValue=(value as AbsNewsLiveReadOutcomeV1).outcomeDigest;}const expected=hmacSha256Tag(this.#key,{kind:row.kind,scope:this.#scope,id:row.record_id,digest:row.record_digest,semantic:row.semantic_key,version:Number(row.version),payloadDigest:sha256Digest(value),recordedAt:row.recorded_at});if(row.record_digest!==digestValue||row.record_auth_tag!==expected)throw new ProjectWorkspaceContractErrorV1("integrity_failed");return value;}
  private current(kind:Kind,idValue:string):Row|undefined{return this.#db.prepare("SELECT * FROM abs_news_live_read_records WHERE kind=? AND record_id=? ORDER BY version DESC LIMIT 1").get(kind,idValue) as Row|undefined;}
  private bySemantic(kind:Kind,key:string):Row|undefined{return this.#db.prepare("SELECT * FROM abs_news_live_read_records WHERE kind=? AND semantic_key=? ORDER BY version DESC LIMIT 1").get(kind,key) as Row|undefined;}
  private currentRows(kind:Kind):Row[]{return this.#db.prepare("SELECT r.* FROM abs_news_live_read_records r JOIN (SELECT record_id,max(version) version FROM abs_news_live_read_records WHERE kind=? GROUP BY record_id) c ON c.record_id=r.record_id AND c.version=r.version WHERE r.kind=? ORDER BY r.record_id").all(kind,kind) as unknown as Row[];}
  private createSchema():void{this.#db.exec("BEGIN IMMEDIATE; CREATE TABLE abs_news_live_read_metadata(tenant_id TEXT NOT NULL,workspace_id TEXT NOT NULL,project_id TEXT NOT NULL,revision INTEGER NOT NULL,record_count INTEGER NOT NULL,state_digest TEXT NOT NULL,state_auth_tag TEXT NOT NULL); CREATE TABLE abs_news_live_read_records(kind TEXT NOT NULL,record_id TEXT NOT NULL,record_digest TEXT NOT NULL,semantic_key TEXT NOT NULL,version INTEGER NOT NULL,payload TEXT NOT NULL,record_auth_tag TEXT NOT NULL,recorded_at TEXT NOT NULL,PRIMARY KEY(kind,record_id,version),UNIQUE(kind,record_digest)); CREATE INDEX abs_news_live_semantic ON abs_news_live_read_records(kind,semantic_key,version); PRAGMA user_version=1; COMMIT;");}
  private initialize():void{const state=this.state(),revision=1;this.#db.prepare("INSERT INTO abs_news_live_read_metadata VALUES(?,?,?,?,?,?,?)").run(this.#scope.tenantId,this.#scope.workspaceId,this.#scope.projectId,revision,state.recordCount,state.stateDigest,hmacSha256Tag(this.#key,this.metaMaterial(revision,state.recordCount,state.stateDigest)));}
  private state():{recordCount:number;stateDigest:string}{const rows=this.#db.prepare("SELECT * FROM abs_news_live_read_records ORDER BY kind,record_id,version").all() as unknown as Row[],records=rows.map((row)=>{this.verified(row);return{kind:row.kind,id:row.record_id,digest:row.record_digest,semantic:row.semantic_key,version:Number(row.version),tag:row.record_auth_tag};});return{recordCount:rows.length,stateDigest:sha256Digest({scope:this.#scope,records})};}
  private advance():void{const meta=this.meta(),state=this.state(),revision=Number(meta.revision)+1,result=this.#db.prepare("UPDATE abs_news_live_read_metadata SET revision=?,record_count=?,state_digest=?,state_auth_tag=? WHERE revision=?").run(revision,state.recordCount,state.stateDigest,hmacSha256Tag(this.#key,this.metaMaterial(revision,state.recordCount,state.stateDigest)),meta.revision);if(Number(result.changes)!==1)throw new ProjectWorkspaceContractErrorV1("integrity_failed");}
  private meta():Meta{const rows=this.#db.prepare("SELECT * FROM abs_news_live_read_metadata").all() as unknown as Meta[];if(rows.length!==1)throw new ProjectWorkspaceContractErrorV1("integrity_failed");return rows[0]!;}
  private metaMaterial(revision:number,recordCount:number,stateDigest:string){return{kind:"metadata",scope:this.#scope,revision,recordCount,stateDigest};}
  private schema():void{const tables=(this.#db.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all() as unknown as {name:string}[]).map((row)=>row.name);if(tables.join("|")!==TABLES.join("|"))throw new ProjectWorkspaceContractErrorV1("integrity_failed");}
  private scope(value:{tenantId:string;workspaceId:string;projectId:string}):void{if(value.tenantId!==this.#scope.tenantId||value.workspaceId!==this.#scope.workspaceId||value.projectId!==this.#scope.projectId)throw new ProjectWorkspaceContractErrorV1("scope_mismatch");}
  private open():void{if(this.#closed)throw new ProjectWorkspaceContractErrorV1("integrity_failed");}
  private transaction<T>(operation:()=>T):T{this.#db.exec("BEGIN IMMEDIATE");try{const result=operation();this.#db.exec("COMMIT");return result;}catch(error){try{this.#db.exec("ROLLBACK");}catch{void 0;}throw error;}}
}
