import { sha256Digest } from "../../security";
import { hermesBotModeManifestV1 } from "./hermes-bot-mode-adapter";
import {
  HERMES_BOT_MODE_OBSERVATION_V1,
  HERMES_BOT_MODE_RESOURCE_CEILINGS_V1,
  type HermesBotModeCompatibilityEvidenceV1,
  type HermesBotModeObservationV1,
} from "./hermes-bot-mode-types";

const digest = (kind: string, id: string): string => sha256Digest({ fixture: "cr11a-team-040", kind, id });

export const hermesBotModeCompatibilityEvidenceFixtureV1: HermesBotModeCompatibilityEvidenceV1 = Object.freeze({
  hermesPackageVersion: hermesBotModeManifestV1.hermesPackageVersion,
  hermesRevision: hermesBotModeManifestV1.hermesRevision,
  observationContract: HERMES_BOT_MODE_OBSERVATION_V1,
  sourceMode: "injected_only",
  readCapabilities: ["profiles", "rooms", "routines", "safe_summary_events"],
  writeCapabilities: [],
  nativeQualified: false,
  sharesProviderAccess: false,
  fullMessageReads: false,
});

export function buildHermesBotModeFixtureV1(projectId = "project.test.hermes-bot"): HermesBotModeObservationV1 {
  const architectProfile = digest("profile", "architect");
  const researcherProfile = digest("profile", "researcher");
  const roomKeyDigest = digest("room", "build-review");
  return {
    contractVersion: HERMES_BOT_MODE_OBSERVATION_V1,
    sourceMode: "injected_only",
    tenantId: "tenant.owner",
    workspaceId: "workspace.control-room",
    projectId,
    observedAt: "2026-08-30T15:00:00.000Z",
    evaluatedAt: "2026-08-30T15:00:30.000Z",
    collectionTruth: { profiles: "observed", routines: "observed", rooms: "observed", events: "observed" },
    profiles: [
      {
        profileKeyDigest: architectProfile,
        identityEvidenceDigest: digest("identity", "architect-mac"),
        projectId,
        displayName: "Marvin",
        handle: "marvin",
        role: "Mac build worker",
        deviceKeyDigest: digest("device", "mac-mini"),
        deviceLabel: "Mac mini",
        platform: "macos",
        modelClass: "hermes.pinned.local",
        sourceState: "enabled",
        queuedWorkCount: 1,
        needsOwner: false,
        reviewedPackageIds: ["package.agent-build-worker.v2"],
        sharedProviderAccess: false,
        fullProfileIncluded: false,
      },
      {
        profileKeyDigest: researcherProfile,
        identityEvidenceDigest: digest("identity", "researcher-mac"),
        projectId,
        displayName: "Scout",
        handle: "scout",
        role: "Research observer",
        deviceKeyDigest: digest("device", "mac-mini"),
        deviceLabel: "Mac mini",
        platform: "macos",
        modelClass: "hermes.pinned.local",
        sourceState: "unknown",
        queuedWorkCount: 0,
        needsOwner: true,
        reviewedPackageIds: ["package.research-source-verification.v1"],
        sharedProviderAccess: false,
        fullProfileIncluded: false,
      },
    ],
    presenceEvidence: [{
      profileKeyDigest: architectProfile,
      projectId,
      basis: "authenticated_heartbeat",
      evidenceDigest: digest("presence", "architect-heartbeat"),
      observedAt: "2026-08-30T14:59:45.000Z",
      validUntil: "2026-08-30T15:04:45.000Z",
      currentWorkItemId: "work.cr11a.team-040",
      currentWorkSummary: "Normalizing an injected read-only Bot Mode fixture.",
    }],
    routines: [
      {
        routineKeyDigest: digest("routine", "build-brief"),
        scheduleKeyDigest: digest("schedule", "build-brief"),
        projectId,
        profileKeyDigest: architectProfile,
        label: "Build brief",
        safeSummary: "A read-only projection of the next reviewed build brief.",
        state: "scheduled",
        nextOccurrenceAt: "2026-08-31T15:00:00.000Z",
        lastOutcomeCode: "completed_safe",
        needsOwner: false,
        scheduleObservedOnly: true,
        commandCapable: false,
        providerAccess: false,
      },
      {
        routineKeyDigest: digest("routine", "source-watch"),
        scheduleKeyDigest: digest("schedule", "source-watch"),
        projectId,
        profileKeyDigest: researcherProfile,
        label: "Source watch",
        safeSummary: "A blocked read-only research routine projection.",
        state: "unknown",
        needsOwner: true,
        scheduleObservedOnly: true,
        commandCapable: false,
        providerAccess: false,
      },
    ],
    rooms: [{
      roomKeyDigest,
      projectId,
      label: "Build review",
      purpose: "review",
      state: "needs_owner",
      memberProfileKeyDigests: [architectProfile, researcherProfile],
      currentRound: 2,
      events: [
        {
          eventKeyDigest: digest("event", "build-review-1"),
          sequence: 1,
          round: 1,
          authorKind: "agent",
          authorProfileKeyDigest: architectProfile,
          safeSummary: "The adapter contract is ready for bounded review.",
          mentionedProfileKeyDigests: [researcherProfile],
          mentionsOwner: false,
          needsOwner: false,
          occurredAt: "2026-08-30T14:55:00.000Z",
          fullMessageIncluded: false,
          providerOutputIncluded: false,
        },
        {
          eventKeyDigest: digest("event", "build-review-2"),
          sequence: 2,
          round: 1,
          authorKind: "agent",
          authorProfileKeyDigest: researcherProfile,
          safeSummary: "The room projection needs an explicit owner decision.",
          mentionedProfileKeyDigests: [],
          mentionsOwner: true,
          needsOwner: true,
          occurredAt: "2026-08-30T14:56:00.000Z",
          fullMessageIncluded: false,
          providerOutputIncluded: false,
        },
        {
          eventKeyDigest: digest("event", "build-review-3"),
          sequence: 3,
          round: 2,
          authorKind: "system",
          safeSummary: "The bounded room paused at the owner-review boundary.",
          mentionedProfileKeyDigests: [],
          mentionsOwner: true,
          needsOwner: true,
          occurredAt: "2026-08-30T14:57:00.000Z",
          fullMessageIncluded: false,
          providerOutputIncluded: false,
        },
      ],
      linkedWorkItemIds: ["work.cr11a.team-040"],
      linkedIncidentIds: [],
      needsOwner: true,
      fullMessagesIncluded: false,
      sharedProviderAccess: false,
      createsWorkItems: false,
      dispatchesWork: false,
    }],
    resourceCeilings: HERMES_BOT_MODE_RESOURCE_CEILINGS_V1,
    nativeQualified: false,
    rpcObserved: false,
    networkObserved: false,
    retainsFullMessages: false,
    sharesProviderAccess: false,
    createsSchedules: false,
    createsWorkItems: false,
    dispatchesWork: false,
    grantsApproval: false,
    grantsLeaseAuthority: false,
    grantsCommandAuthority: false,
    grantsExecutionAuthority: false,
  };
}

export function buildUnknownHermesBotModeFixtureV1(projectId = "project.test.hermes-bot-empty"): HermesBotModeObservationV1 {
  return {
    contractVersion: HERMES_BOT_MODE_OBSERVATION_V1,
    sourceMode: "injected_only",
    tenantId: "tenant.owner",
    workspaceId: "workspace.control-room",
    projectId,
    observedAt: "2026-08-30T15:00:00.000Z",
    evaluatedAt: "2026-08-30T15:00:30.000Z",
    collectionTruth: { profiles: "unknown", routines: "absent", rooms: "unknown", events: "unknown" },
    profiles: [],
    presenceEvidence: [],
    routines: [],
    rooms: [],
    resourceCeilings: HERMES_BOT_MODE_RESOURCE_CEILINGS_V1,
    nativeQualified: false,
    rpcObserved: false,
    networkObserved: false,
    retainsFullMessages: false,
    sharesProviderAccess: false,
    createsSchedules: false,
    createsWorkItems: false,
    dispatchesWork: false,
    grantsApproval: false,
    grantsLeaseAuthority: false,
    grantsCommandAuthority: false,
    grantsExecutionAuthority: false,
  };
}
