/**
 * Minimal Control Room binding to the sanitized schema generated by the exact
 * selected Codex App Server package. This is deliberately not a vendored copy
 * of the upstream protocol and exposes no general request capability.
 */
export const CODEX_APP_SERVER_READ_CONTRACT = Object.freeze({
  package: '@openai/codex' as const,
  version: '0.150.0-alpha.8' as const,
  generatedBundleSha256: 'fef60935ec72c842ed361ce064693691e415b0f45a2c1351bda13c6013b0a7bf' as const,
  method: 'thread/read' as const,
  includeTurns: true as const,
  resultRequired: Object.freeze(['thread'] as const),
  threadRequiredForProjection: Object.freeze(['id', 'turns'] as const),
  turnRequiredForProjection: Object.freeze(['id', 'status'] as const),
  turnStatuses: Object.freeze(['completed', 'interrupted', 'failed', 'inProgress'] as const),
});
