// A stage that reproduces the ledger-position collision rv-mr5o Finding 1
// describes, at small numbers, against the real production applier.
//
// WHY THE COLLISION IS NOT VISIBLE IN ONE TREE.
// `generate-migration-ledger.mjs` assigns `order` sequentially over
// `db/migrations/*.sql` sorted lexicographically, so a MERGED tree never contains
// two files at one ledger order. The collision is between a MERGED LEDGER and a
// DATABASE already migrated from one branch's ledger:
//
//   branch A: 0001, 0002, 0003_branch_a        -> the database records
//              0003_branch_a at ledger_order 3.
//   branch B: 0001, 0002, 0002b_branch_b       -> merged, 0002b sorts AHEAD of
//              0003_branch_a, so in the merged ledger order 3 is
//              0002b_branch_b and 0003_branch_a is pushed to order 4.
//
// Both branches added exactly one migration above the same last shipped file,
// and the database is at branch A's real head. The review measured this on the
// real r5bk/int7 ledgers; this is the same shape with four tiny files so the
// test can assert on what DID and DID NOT run.
//
// Each synthetic migration creates a real table, so "half-applied" is observable
// through `to_regclass` rather than inferred from a message.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { collectLedgerEntries, ledgerDigest } from "../../scripts/generate-migration-ledger.mjs";

/** The synthetic migrations, by name, in the branch each one belongs to. */
export const COLLISION_BASE = Object.freeze(["0001_base.sql", "0002_base.sql"]);
export const COLLISION_BRANCH_A = "0003_branch_a.sql";
export const COLLISION_BRANCH_B = "0002b_branch_b.sql";
/**
 * Branch B's migration under the name the OPERATOR'S REMEDY gives it.
 *
 * Renumbering it does not mean editing it -- it means naming it so it sorts AFTER
 * the applied head, because the whole collision is that `0002b` sorts before
 * `0003`. The SQL is byte-identical to `COLLISION_BRANCH_B`'s, so the remedy stage
 * changes the ledger and nothing else, which is what a renumber is.
 */
export const COLLISION_BRANCH_RENAMED = "0004_branch_b_renumbered.sql";
/** Branch A's real head: the shared base plus the migration A added. */
export const COLLISION_LEDGER_A = Object.freeze([...COLLISION_BASE, COLLISION_BRANCH_A]);
/** The merged tree: both branches' additions, in the order the generator sorts them. */
export const COLLISION_LEDGER_MERGED = Object.freeze(
  [...COLLISION_BASE, COLLISION_BRANCH_B, COLLISION_BRANCH_A].sort());

/** Branch B's SQL, named once so the two filenames cannot drift apart. */
const SQL_BRANCH_B = "CREATE TABLE collision_branch_b (id integer PRIMARY KEY, note text NOT NULL DEFAULT '');\n";

const SQL: Readonly<Record<string, string>> = Object.freeze({
  [COLLISION_BRANCH_A]: "CREATE TABLE collision_branch_a (id integer PRIMARY KEY, note text NOT NULL DEFAULT '');\n",
  [COLLISION_BRANCH_B]: SQL_BRANCH_B,
  "0001_base.sql": "CREATE TABLE collision_base_one (id integer PRIMARY KEY, note text NOT NULL DEFAULT '');\n",
  "0002_base.sql": "CREATE TABLE collision_base_two (id integer PRIMARY KEY, note text NOT NULL DEFAULT '');\n",
  // Byte-identical to branch B's own file: only the NAME differs, and the name is
  // the whole of the remedy.
  [COLLISION_BRANCH_RENAMED]: SQL_BRANCH_B,
});

/** The table each collision migration creates: the evidence a half-apply would leave. */
export const COLLISION_TABLE_FOR_FILE = Object.freeze({
  [COLLISION_BRANCH_A]: "collision_branch_a",
  [COLLISION_BRANCH_B]: "collision_branch_b",
});

/**
 * One ledger entry, as `collectLedgerEntries` produces it. Derived from the
 * generator rather than restated: a hand-written union silently stopped matching
 * the moment the generator grew a kind.
 */
export type CollisionLedgerEntry = Awaited<ReturnType<typeof collectLedgerEntries>>[number];

/** What a staged tree hands back: where its ledger is, and what it covers. */
export interface CollisionStage {
  stage: string;
  ledgerPath: string;
  entries: readonly CollisionLedgerEntry[];
  migrate: readonly CollisionLedgerEntry[];
}

/**
 * A stage carrying exactly `migrations`, plus the real role files and the real
 * ledger-table DDL, with its ledger generated by the repository's own generator.
 *
 * `repositoryRoot` is only read for those five real files; the synthetic
 * migrations are written from `SQL`. A synthetic file that is not one of the four
 * is refused by name rather than written as an empty migration.
 *
 * @param stage the directory to create the stage in
 * @param migrations exactly the migration filenames to stage
 * @param repositoryRoot the checkout the real role/setup files come from
 */
export async function stageCollisionLedger(stage: string, migrations: readonly string[],
  repositoryRoot: string): Promise<CollisionStage> {
  await mkdir(join(stage, "deploy/postgres"), { recursive: true });
  await mkdir(join(stage, "db/migrations"), { recursive: true });
  await mkdir(join(stage, "db/roles"), { recursive: true });
  await mkdir(join(stage, "db/setup"), { recursive: true });
  for (const file of ["production_roles.sql", "production_table_grants.sql",
    "agent_reviewer_roles.sql", "production_provision.sql"])
    await writeFile(join(stage, "db/roles", file), await readFile(join(repositoryRoot, "db/roles", file), "utf8"));
  await writeFile(join(stage, "db/setup/production_migration_ledger.sql"),
    await readFile(join(repositoryRoot, "db/setup/production_migration_ledger.sql"), "utf8"));
  for (const file of migrations) {
    const sql: string | undefined = SQL[file];
    if (sql === undefined) throw new Error(`collision_stage_unknown_migration:${file}`);
    await writeFile(join(stage, "db/migrations", file), sql);
  }
  const entries: readonly CollisionLedgerEntry[] = await collectLedgerEntries(stage);
  const ledgerPath = join(stage, "deploy/postgres/migration-ledger.json");
  await writeFile(ledgerPath, `${JSON.stringify({ version: 1, digest: ledgerDigest(entries), entries }, null, 2)}\n`);
  return {
    stage,
    ledgerPath,
    entries,
    migrate: entries.filter(entry => (entry.kind ?? "migrate") === "migrate"),
  };
}