import {assertNoSecretMaterial} from "../../security/redaction";
import {createHostResultCollectorV1,dataMethodV1,exactHostUint8ArrayV1,isHostProxyV1,wipeHostUint8ArrayV1} from "../../security/host-value";
import {SafeCredentialCatalogV1} from "./catalog";
import {buildSecretInvocationGrantV1,parseSecretInvocationGrantV1} from "./grant";
import {secretConsumerResultSchemaV1,secretInvocationReceiptSchemaV1} from "./schemas";
import {SECRET_BROKER_CONTRACT_V1,type BuildSecretInvocationGrantInputV1,type NodeLocalSecretConsumerV1,type NodeLocalSecretProviderV1,type SecretConsumerResultV1,type SecretInvocationGrantV1,type SecretInvocationReceiptV1,type SecretProviderAcquisitionV1} from "./types";
import type {SecretInvocationLedgerV1} from "./types";
import {exactDataArrayV1,exactDataSnapshotV1,ownDataValueV1} from "./exact-data";

interface LedgerRecord{grantDigest:string;state:"claimed"|"succeeded"|"failed"|"ambiguous";receipt?:SecretInvocationReceiptV1;}
const providerUnavailableCodes=new Set(["locked","interaction_required","missing","permission_denied","revoked","unavailable_platform"]);
function parseExactConsumerResultV1(value:unknown):SecretConsumerResultV1{
  const outcome=ownDataValueV1(value,"outcome"),keys=outcome==="succeeded"?["outcome","outputDigest"]:outcome==="definite_failure"||outcome==="ambiguous"?["outcome","safeCode"]:undefined;
  const snapshot=keys?exactDataSnapshotV1(value,keys):undefined;if(!snapshot)throw new Error("credential consumer result invalid");return secretConsumerResultSchemaV1.parse(snapshot);
}
async function discardAcquisitionV1(value:unknown):Promise<void>{const material=ownDataValueV1(value,"material"),release=ownDataValueV1(value,"release");wipeHostUint8ArrayV1(material);try{if(typeof release==="function"&&!isHostProxyV1(release))await release();}catch{void 0;}}
export class InMemorySecretInvocationLedgerV1 implements SecretInvocationLedgerV1{
  readonly #authorized=new Map<string,SecretInvocationGrantV1>();readonly #records=new Map<string,LedgerRecord>();
  authorize(grant:SecretInvocationGrantV1){const known=this.#authorized.get(grant.invocationId);if(known&&known.grantDigest!==grant.grantDigest)throw new Error("invocation authorization conflict");if(!known)this.#authorized.set(grant.invocationId,structuredClone(grant));return structuredClone(known??grant);}
  terminalReceipt(grant:SecretInvocationGrantV1){const authorized=this.#authorized.get(grant.invocationId);if(!authorized||authorized.grantDigest!==grant.grantDigest)return undefined;const receipt=this.#records.get(grant.invocationId)?.receipt;return receipt?structuredClone(receipt):undefined;}
  claim(grant:SecretInvocationGrantV1,claimedAt:string){void claimedAt;const authorized=this.#authorized.get(grant.invocationId);if(!authorized||authorized.grantDigest!==grant.grantDigest)throw new Error("invocation not authorized by local broker");const known=this.#records.get(grant.invocationId);if(known?.receipt)return{disposition:"terminal" as const,receipt:known.receipt};if(known)return{disposition:"in_progress" as const};this.#records.set(grant.invocationId,{grantDigest:grant.grantDigest,state:"claimed"});return{disposition:"dispatch" as const};}
  settle(grant:SecretInvocationGrantV1,receipt:SecretInvocationReceiptV1){const record=this.#records.get(grant.invocationId);if(!record||record.grantDigest!==grant.grantDigest)throw new Error("invocation settlement conflict");if(record.receipt){if(JSON.stringify(record.receipt)!==JSON.stringify(receipt))throw new Error("invocation settlement conflict");return structuredClone(record.receipt);}record.state=receipt.state;record.receipt=structuredClone(receipt);return structuredClone(receipt);}
  receipts(){return[...this.#records.values()].flatMap((value)=>value.receipt?[structuredClone(value.receipt)]:[]);}
}
export class NodeLocalSecretBrokerV1{
  readonly #providers=new Map<string,NodeLocalSecretProviderV1>();
  constructor(private readonly catalog:SafeCredentialCatalogV1,providers:NodeLocalSecretProviderV1[],private readonly ledger:SecretInvocationLedgerV1=new InMemorySecretInvocationLedgerV1(),private readonly options:{allowEffectFreeProviderAdapters?:boolean;clock?:()=>string}={}){const providerValues=exactDataArrayV1(providers,500);if(!providerValues)throw new Error("credential providers invalid");let hasProviderAdapter=false;for(const value of providerValues){const provider=value as NodeLocalSecretProviderV1,kind=ownDataValueV1(provider,"providerKind"),acquire=dataMethodV1(provider,"acquire");if(!["synthetic_test","bitwarden","onepassword","destination_native"].includes(kind as string)||!acquire)throw new Error("credential provider invalid");if(kind!=="synthetic_test"){hasProviderAdapter=true;if(!options.allowEffectFreeProviderAdapters)throw new Error("live credential providers are disabled in CR8E-001/002/003");}if(this.#providers.has(kind as string))throw new Error("duplicate credential provider");this.#providers.set(kind as string,{providerKind:kind as NodeLocalSecretProviderV1["providerKind"],acquire:acquire.bind(provider) as NodeLocalSecretProviderV1["acquire"]});}if(hasProviderAdapter&&(!options.clock||isHostProxyV1(options.clock)))throw new Error("provider adapters require a broker-owned clock");}
  authorize(input:Omit<BuildSecretInvocationGrantInputV1,"entry">):SecretInvocationGrantV1{const entry=this.catalog.resolve(input.credentialRef);if(!entry)throw new Error("credential unavailable");return this.ledger.authorize(buildSecretInvocationGrantV1({...input,entry}));}
  async invoke(input:{grant:unknown;consumer:NodeLocalSecretConsumerV1;now:string}):Promise<SecretInvocationReceiptV1>{const grant=parseSecretInvocationGrantV1(input.grant),terminal=this.ledger.terminalReceipt(grant);if(terminal)return terminal;const startedAt=this.options.clock?.()??input.now;const finishObservation=()=>{const observed=this.options.clock?.()??startedAt,trustworthy=Number.isFinite(Date.parse(observed))&&Date.parse(observed)>=Date.parse(startedAt);return{recordedAt:trustworthy?observed:startedAt,trustworthy};};
    const entry=this.catalog.resolve(grant.credentialRef);if(!entry||entry.entryDigest!==grant.catalogEntryDigest||entry.state!=="active")throw new Error("credential unavailable");
    if(entry.tenantId!==grant.tenantId||entry.nodeId!==grant.nodeId||!entry.projectIds.includes(grant.projectId)||!entry.executorIds.includes(grant.executorId)||!entry.operationIds.includes(grant.operationId)||!entry.purposeIds.includes(grant.purposeId))throw new Error("credential scope denied");
    if(!Number.isFinite(Date.parse(startedAt))||Date.parse(startedAt)<Date.parse(grant.issuedAt)||Date.parse(startedAt)>=Date.parse(grant.expiresAt))throw new Error("credential invocation expired");
    const claim=this.ledger.claim(grant,startedAt);if(claim.disposition==="terminal")return claim.receipt;if(claim.disposition==="in_progress")throw new Error("invocation in progress");
    const provider=this.#providers.get(entry.providerKind);if(!provider)return this.finish(grant,"failed","provider_unavailable",finishObservation().recordedAt);
    let acquired;const providerResult=createHostResultCollectorV1();try{await provider.acquire({credentialRef:grant.credentialRef,providerReferenceDigest:entry.providerReferenceDigest,invocationId:grant.invocationId},providerResult.collector);acquired=providerResult.take();}catch{await discardAcquisitionV1(providerResult.abort());return this.finish(grant,"ambiguous","provider_outcome_unknown",finishObservation().recordedAt);}
    try{const status=ownDataValueV1(acquired,"status"),unavailable=exactDataSnapshotV1(acquired,["status","safeCode"]),resolved=exactDataSnapshotV1(acquired,["status","material","release"]),material=resolved&&exactHostUint8ArrayV1(resolved.material,65_536),validUnavailable=status==="unavailable"&&unavailable&&providerUnavailableCodes.has(unavailable.safeCode as string),validResolved=status==="resolved"&&resolved&&material&&material.byteLength>0&&typeof resolved.release==="function"&&!isHostProxyV1(resolved.release);if(!validUnavailable&&!validResolved)throw new Error("provider result invalid");if(validUnavailable)acquired=unavailable;else{const providerRelease=resolved!.release as ()=>Promise<void>,consumerMaterial=material!.copy();acquired={status:"resolved",material:consumerMaterial,release:async()=>{material!.wipe();await providerRelease();}};} }
    catch{await discardAcquisitionV1(acquired);return this.finish(grant,"ambiguous","provider_result_invalid",finishObservation().recordedAt);}
    const safeAcquired=acquired as SecretProviderAcquisitionV1;
    if(safeAcquired.status==="unavailable"){const observed=finishObservation();return !observed.trustworthy||Date.parse(observed.recordedAt)>=Date.parse(grant.expiresAt)?this.finish(grant,"ambiguous","provider_outcome_unknown",observed.recordedAt):this.finish(grant,"failed",`provider_${safeAcquired.safeCode}`,observed.recordedAt);}
    let result;let uncertain=false;const consumerResult=createHostResultCollectorV1();try{const consume=dataMethodV1(input.consumer,"consume");if(!consume)throw new Error("credential consumer invalid");await consume.call(input.consumer,safeAcquired.material,{invocationId:grant.invocationId,tenantId:grant.tenantId,nodeId:grant.nodeId,projectId:grant.projectId,jobId:grant.jobId,attemptId:grant.attemptId,executorId:grant.executorId,operationId:grant.operationId,purposeId:grant.purposeId},consumerResult.collector);result=parseExactConsumerResultV1(consumerResult.take());assertNoSecretMaterial(result,"credential consumer result");}catch{consumerResult.abort();uncertain=true;}
    finally{wipeHostUint8ArrayV1(safeAcquired.material);try{await safeAcquired.release();}catch{uncertain=true;}}
    const observedSettlement=finishObservation(),settledAt=observedSettlement.recordedAt;if(!observedSettlement.trustworthy||Date.parse(settledAt)>=Date.parse(grant.expiresAt))uncertain=true;
    if(uncertain||!result)return this.finish(grant,"ambiguous","consumer_or_cleanup_outcome_unknown",settledAt);
    if(result.outcome==="succeeded")return this.finish(grant,"succeeded","completed",settledAt,result.outputDigest);
    if(result.outcome==="definite_failure")return this.finish(grant,"failed",result.safeCode,settledAt);
    return this.finish(grant,"ambiguous",result.safeCode,settledAt);
  }
  safeLedger():SecretInvocationReceiptV1[]{const values=this.ledger.receipts();assertNoSecretMaterial(values,"credential invocation ledger");return structuredClone(values);}
  private finish(grant:SecretInvocationGrantV1,state:"succeeded"|"failed"|"ambiguous",safeCode:string,recordedAt:string,outputDigest?:string){const receipt=secretInvocationReceiptSchemaV1.parse({contractVersion:SECRET_BROKER_CONTRACT_V1,invocationId:grant.invocationId,credentialRef:grant.credentialRef,state,safeCode,...(outputDigest?{outputDigest}:{}),recordedAt,grantsApproval:false,grantsExecutionAuthority:false}) as SecretInvocationReceiptV1;return this.ledger.settle(grant,receipt);}
}
