import {sha256Digest} from "../../security/digest";
import {createHostResultCollectorV1,dataMethodV1,exactHostUint8ArrayV1,isHostProxyV1,wipeHostUint8ArrayV1,type HostResultCollectorV1} from "../../security/host-value";
import type {CredentialProviderKindV1,NodeLocalSecretProviderV1,SecretProviderAcquisitionV1,SecretProviderResultCollectorV1,SecretProviderUnavailableCodeV1} from "./types";
import {exactDataArrayV1,exactDataSnapshotV1,ownDataValueV1} from "./exact-data";

export interface ProviderCommandPlanV1 {executablePath:string;expectedBinaryDigest:string;args:string[];shell:false;interactive:false;inheritEnvironment:false;stdin:"none";timeoutMilliseconds:number;maximumOutputBytes:number;}
export type ProviderRunnerResultV1=
  |{status:"completed";exitCode:number;stdout:Uint8Array;observedBinaryDigest:string;stderrDigest:string;safeCode?:SecretProviderUnavailableCodeV1}
  |{status:"not_started";safeCode:SecretProviderUnavailableCodeV1}
  |{status:"outcome_unknown";safeCode:string};
export interface ProviderRunnerResultCollectorV1 {submit(value:unknown):void;}
export interface InjectedProviderRunnerV1 {run(plan:ProviderCommandPlanV1,result:ProviderRunnerResultCollectorV1):Promise<void>;}
export interface PrivateProviderBindingV1 {credentialRef:string;providerReference:string;providerReferenceDigest:string;}
export interface CliProviderConfigurationV1 {executablePath:string;expectedBinaryDigest:string;timeoutMilliseconds:number;maximumOutputBytes:number;bindings:PrivateProviderBindingV1[];}

const digest=/^sha256:[a-f0-9]{64}$/;const safeId=/^[a-zA-Z0-9][a-zA-Z0-9._:-]{2,179}$/;
const unavailableCodes=new Set<SecretProviderUnavailableCodeV1>(["locked","interaction_required","missing","permission_denied","revoked","unavailable_platform"]);
function validateConfig(config:CliProviderConfigurationV1,kind:CredentialProviderKindV1,reference:(value:string)=>boolean){const snapshot=exactDataSnapshotV1(config,["executablePath","expectedBinaryDigest","timeoutMilliseconds","maximumOutputBytes","bindings"]),bindings=exactDataArrayV1(snapshot?.bindings,500);if(!snapshot||typeof snapshot.executablePath!=="string"||!snapshot.executablePath.startsWith("/")||snapshot.executablePath.includes("\0")||typeof snapshot.expectedBinaryDigest!=="string"||!digest.test(snapshot.expectedBinaryDigest)||!Number.isInteger(snapshot.timeoutMilliseconds)||Number(snapshot.timeoutMilliseconds)<100||Number(snapshot.timeoutMilliseconds)>30_000||!Number.isInteger(snapshot.maximumOutputBytes)||Number(snapshot.maximumOutputBytes)<1||Number(snapshot.maximumOutputBytes)>65_536||!bindings||bindings.length<1)throw new Error(`${kind} provider configuration invalid`);
  const known=new Set<string>();for(const value of bindings){const item=exactDataSnapshotV1(value,["credentialRef","providerReference","providerReferenceDigest"]);if(!item||typeof item.credentialRef!=="string"||typeof item.providerReference!=="string"||typeof item.providerReferenceDigest!=="string"||!safeId.test(item.credentialRef)||known.has(item.credentialRef)||!reference(item.providerReference)||sha256Digest({providerReference:item.providerReference})!==item.providerReferenceDigest)throw new Error(`${kind} provider binding invalid`);known.add(item.credentialRef);}}
function binding(config:CliProviderConfigurationV1,input:{credentialRef:string;providerReferenceDigest:string}){const item=config.bindings.find((value)=>value.credentialRef===input.credentialRef);if(!item||item.providerReferenceDigest!==input.providerReferenceDigest)return undefined;return item;}
function plan(config:CliProviderConfigurationV1,args:string[]):ProviderCommandPlanV1{return{executablePath:config.executablePath,expectedBinaryDigest:config.expectedBinaryDigest,args,shell:false,interactive:false,inheritEnvironment:false,stdin:"none",timeoutMilliseconds:config.timeoutMilliseconds,maximumOutputBytes:config.maximumOutputBytes};}
function materialFrom(result:Extract<ProviderRunnerResultV1,{status:"completed"}>,config:CliProviderConfigurationV1,stripLineEnding:boolean):SecretProviderAcquisitionV1{const observed=exactHostUint8ArrayV1(result.stdout,65_536),fail=(message:string)=>{wipeHostUint8ArrayV1(result.stdout);throw new Error(message);};if(!observed)throw new Error("provider result invalid");if(!Number.isInteger(result.exitCode)||!digest.test(result.observedBinaryDigest)||!digest.test(result.stderrDigest))return fail("provider result invalid");if(result.observedBinaryDigest!==config.expectedBinaryDigest)return fail("provider binary identity mismatch");
  if(result.exitCode!==0){observed.wipe();return{status:"unavailable",safeCode:result.safeCode??"permission_denied"};}if(observed.byteLength<1||observed.byteLength>config.maximumOutputBytes)return fail("provider output bound invalid");let end=observed.byteLength;if(stripLineEnding&&end>0&&observed.byteAt(end-1)===10){end--;if(end>0&&observed.byteAt(end-1)===13)end--;}
  if(end<1)return fail("provider output invalid");let material:Uint8Array;try{material=observed.copy(end);}finally{observed.wipe();}return{status:"resolved",material,release:async()=>{wipeHostUint8ArrayV1(material);}};}
function validateRunnerResult(value:unknown):ProviderRunnerResultV1{const zero=()=>{wipeHostUint8ArrayV1(ownDataValueV1(value,"stdout"));},status=ownDataValueV1(value,"status");
  if(status==="not_started"){const candidate=exactDataSnapshotV1(value,["status","safeCode"]);if(!candidate||!unavailableCodes.has(candidate.safeCode as SecretProviderUnavailableCodeV1)){zero();throw new Error("provider result invalid");}return candidate as unknown as Extract<ProviderRunnerResultV1,{status:"not_started"}>;}
  if(status==="outcome_unknown"){const candidate=exactDataSnapshotV1(value,["status","safeCode"]);if(!candidate||typeof candidate.safeCode!=="string"||!/^[a-z][a-z0-9_]{2,63}$/.test(candidate.safeCode)){zero();throw new Error("provider result invalid");}return candidate as unknown as Extract<ProviderRunnerResultV1,{status:"outcome_unknown"}>;}
  const hasSafeCode=ownDataValueV1(value,"safeCode")!==undefined,allowed=hasSafeCode?["status","exitCode","stdout","observedBinaryDigest","stderrDigest","safeCode"]:["status","exitCode","stdout","observedBinaryDigest","stderrDigest"],candidate=exactDataSnapshotV1(value,allowed),stdout=candidate?.stdout;
  if(!candidate||candidate.status!=="completed"||!Number.isInteger(candidate.exitCode)||Number(candidate.exitCode)<0||Number(candidate.exitCode)>255||!exactHostUint8ArrayV1(stdout,65_536)||typeof candidate.observedBinaryDigest!=="string"||!digest.test(candidate.observedBinaryDigest)||typeof candidate.stderrDigest!=="string"||!digest.test(candidate.stderrDigest)||(candidate.safeCode!==undefined&&!unavailableCodes.has(candidate.safeCode as SecretProviderUnavailableCodeV1))||(candidate.exitCode===0&&candidate.safeCode!==undefined)){zero();throw new Error("provider result invalid");}
  return candidate as unknown as Extract<ProviderRunnerResultV1,{status:"completed"}>;
}
function wipeCollectedOutput(value:unknown):void{wipeHostUint8ArrayV1(ownDataValueV1(value,"stdout"));}
async function discardNativeAcquisition(value:unknown):Promise<void>{const material=ownDataValueV1(value,"material"),release=ownDataValueV1(value,"release");wipeHostUint8ArrayV1(material);try{if(typeof release==="function"&&!isHostProxyV1(release))await release();}catch{void 0;}}
async function run(config:CliProviderConfigurationV1,runProvider:(plan:ProviderCommandPlanV1,result:HostResultCollectorV1)=>Promise<void>,args:string[],stripLineEnding:boolean){const collected=createHostResultCollectorV1();try{await runProvider(plan(config,args),collected.collector);const result=validateRunnerResult(collected.take());if(result.status==="outcome_unknown")throw new Error("provider runner outcome unknown");if(result.status==="not_started")return{status:"unavailable",safeCode:result.safeCode} as const;return materialFrom(result,config,stripLineEnding);}catch(error){wipeCollectedOutput(collected.abort());throw error;}}

export class BitwardenSecretProviderV1 implements NodeLocalSecretProviderV1{readonly providerKind="bitwarden" as const;readonly #config:CliProviderConfigurationV1;readonly #runProvider:(plan:ProviderCommandPlanV1,result:HostResultCollectorV1)=>Promise<void>;constructor(config:CliProviderConfigurationV1,runner:InjectedProviderRunnerV1){validateConfig(config,this.providerKind,(value)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value));const runProvider=dataMethodV1(runner,"run");if(!runProvider)throw new Error("bitwarden provider runner invalid");this.#runProvider=runProvider.bind(runner) as (plan:ProviderCommandPlanV1,result:HostResultCollectorV1)=>Promise<void>;this.#config=structuredClone(config);validateConfig(this.#config,this.providerKind,(value)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value));}
  async acquire(input:{credentialRef:string;providerReferenceDigest:string;invocationId:string},result:SecretProviderResultCollectorV1){const item=binding(this.#config,input);if(!item){result.submit({status:"unavailable",safeCode:"missing"});return;}result.submit(await run(this.#config,this.#runProvider,["get","password",item.providerReference,"--nointeraction"],true));}}

export class OnePasswordSecretProviderV1 implements NodeLocalSecretProviderV1{readonly providerKind="onepassword" as const;readonly #config:CliProviderConfigurationV1;readonly #runProvider:(plan:ProviderCommandPlanV1,result:HostResultCollectorV1)=>Promise<void>;constructor(config:CliProviderConfigurationV1,runner:InjectedProviderRunnerV1){validateConfig(config,this.providerKind,(value)=>value.length<=512&&/^op:\/\/[^\s/?#]+\/[^\s/?#]+\/[^\s?#]+$/.test(value));const runProvider=dataMethodV1(runner,"run");if(!runProvider)throw new Error("onepassword provider runner invalid");this.#runProvider=runProvider.bind(runner) as (plan:ProviderCommandPlanV1,result:HostResultCollectorV1)=>Promise<void>;this.#config=structuredClone(config);validateConfig(this.#config,this.providerKind,(value)=>value.length<=512&&/^op:\/\/[^\s/?#]+\/[^\s/?#]+\/[^\s?#]+$/.test(value));}
  async acquire(input:{credentialRef:string;providerReferenceDigest:string;invocationId:string},result:SecretProviderResultCollectorV1){const item=binding(this.#config,input);if(!item){result.submit({status:"unavailable",safeCode:"missing"});return;}result.submit(await run(this.#config,this.#runProvider,["read",item.providerReference,"--no-newline"],false));}}

export interface DestinationNativeResolverV1 {resolve(input:{credentialRef:string;providerReference:string;invocationId:string},result:SecretProviderResultCollectorV1):Promise<void>;}
export class DestinationNativeSecretProviderV1 implements NodeLocalSecretProviderV1{readonly providerKind="destination_native" as const;readonly #bindings:PrivateProviderBindingV1[];readonly #resolve:(input:{credentialRef:string;providerReference:string;invocationId:string},result:HostResultCollectorV1)=>Promise<void>;constructor(bindings:PrivateProviderBindingV1[],resolver:DestinationNativeResolverV1){const config={executablePath:"/destination-native",expectedBinaryDigest:"sha256:"+"0".repeat(64),timeoutMilliseconds:100,maximumOutputBytes:1,bindings};validateConfig(config,this.providerKind,(value)=>/^[a-zA-Z0-9][a-zA-Z0-9._:/-]{2,511}$/.test(value));const resolve=dataMethodV1(resolver,"resolve");if(!resolve)throw new Error("destination_native provider resolver invalid");this.#resolve=resolve.bind(resolver) as (input:{credentialRef:string;providerReference:string;invocationId:string},result:HostResultCollectorV1)=>Promise<void>;this.#bindings=structuredClone(bindings);}
  async acquire(input:{credentialRef:string;providerReferenceDigest:string;invocationId:string},providerResult:SecretProviderResultCollectorV1){const item=this.#bindings.find((value)=>value.credentialRef===input.credentialRef&&value.providerReferenceDigest===input.providerReferenceDigest);if(!item){providerResult.submit({status:"unavailable",safeCode:"missing"});return;}const collected=createHostResultCollectorV1();let result:unknown;try{await this.#resolve({credentialRef:item.credentialRef,providerReference:item.providerReference,invocationId:input.invocationId},collected.collector);result=collected.take();}catch(error){await discardNativeAcquisition(collected.abort());throw error;}const status=ownDataValueV1(result,"status"),unavailable=exactDataSnapshotV1(result,["status","safeCode"]),resolved=exactDataSnapshotV1(result,["status","material","release"]),material=resolved&&exactHostUint8ArrayV1(resolved.material,65_536);if(status==="unavailable"&&unavailable&&unavailableCodes.has(unavailable.safeCode as SecretProviderUnavailableCodeV1)){providerResult.submit(unavailable);return;}if(status==="resolved"&&resolved&&material&&material.byteLength>0&&typeof resolved.release==="function"&&!isHostProxyV1(resolved.release)){let copy:Uint8Array|undefined,released=false;const releaseOriginal=async()=>{if(released)return;released=true;await (resolved.release as ()=>Promise<void>)();};try{copy=material.copy();material.wipe();await releaseOriginal();providerResult.submit({status:"resolved",material:copy,release:async()=>{wipeHostUint8ArrayV1(copy);}});return;}catch(error){wipeHostUint8ArrayV1(copy);material.wipe();try{await releaseOriginal();}catch{void 0;}throw error;}}await discardNativeAcquisition(result);throw new Error("destination_native provider result invalid");}}
