import {closeSync,lstatSync,openSync} from "node:fs";
import {dirname} from "node:path";
import {timingSafeEqual} from "node:crypto";
import {DatabaseSync} from "node:sqlite";
import {assertPrivateSqliteSchemaV1} from "../../harness/codex-v1/private-sqlite-schema";
import {hmacSha256Tag} from "../../security/digest";
import {sha256Digest} from "../../security/digest";
import {assertNoSecretMaterial} from "../../security/redaction";
import {ROLLBACK_CHECKPOINT_SCHEMA_V1,rollbackCheckpointDigestV1,type RollbackCheckpointStoreV1,type RollbackCheckpointV1} from "../../security/rollback-checkpoint";
import {parseSecretInvocationGrantV1} from "./grant";
import {secretInvocationReceiptSchemaV1} from "./schemas";
import {SECRET_BROKER_CONTRACT_V1,type SecretInvocationClaimV1,type SecretInvocationGrantV1,type SecretInvocationLedgerV1,type SecretInvocationReceiptV1} from "./types";

type Row={invocation_id:string;grant_digest:string;grant_json:string;state:"authorized"|"claimed"|"succeeded"|"failed"|"ambiguous";receipt_json:string|null;updated_at:string};
const tableSql="CREATE TABLE secret_invocation_records (invocation_id TEXT PRIMARY KEY,grant_digest TEXT NOT NULL,grant_json TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('authorized','claimed','succeeded','failed','ambiguous')),receipt_json TEXT,updated_at TEXT NOT NULL)";
const metadataSql="CREATE TABLE secret_invocation_metadata (singleton INTEGER PRIMARY KEY CHECK(singleton=1),ledger_identity_digest TEXT NOT NULL,revision INTEGER NOT NULL CHECK(revision>=1),high_water_at TEXT NOT NULL,state_auth_tag TEXT NOT NULL)";
const initialHighWater="1970-01-01T00:00:00.000Z";
const validDigest=(value:string)=>/^sha256:[a-f0-9]{64}$/.test(value);
const equal=(left:string,right:string)=>{const a=Buffer.from(left),b=Buffer.from(right);return a.length===b.length&&timingSafeEqual(a,b);};
function preparePath(path:string,mode:"create"|"open"){const uid=process.getuid?.();const parent=lstatSync(dirname(path));if(!parent.isDirectory()||parent.isSymbolicLink()||(uid!==undefined&&parent.uid!==uid)||(process.platform!=="win32"&&(parent.mode&0o077)!==0))throw new Error("credential ledger path is not private");
  try{const file=lstatSync(path);if(mode==="create")throw new Error("credential ledger already exists");if(!file.isFile()||file.isSymbolicLink()||file.nlink!==1||(uid!==undefined&&file.uid!==uid)||(process.platform!=="win32"&&(file.mode&0o077)!==0))throw new Error("credential ledger path is not private");}
  catch(error){if(!(error instanceof Error)||!("code" in error)||error.code!=="ENOENT")throw error;if(mode==="open")throw new Error("credential ledger missing");closeSync(openSync(path,"wx",0o600));}}

interface LedgerMetadataRow{ledger_identity_digest:string;revision:number;high_water_at:string;state_auth_tag:string;}

export class SqliteSecretInvocationLedgerV1 implements SecretInvocationLedgerV1{
  readonly #db:DatabaseSync;readonly #key:Uint8Array;
  readonly #checkpointRead:RollbackCheckpointStoreV1["read"];readonly #checkpointInitialize:RollbackCheckpointStoreV1["initialize"];readonly #checkpointAdvance:RollbackCheckpointStoreV1["advance"];
  constructor(path:string,private readonly ledgerIdentityDigest:string,private readonly options:{integrityKey:Uint8Array;checkpointStore:RollbackCheckpointStoreV1;mode:"create"|"open";testOnlyAllowEphemeral?:boolean;clock?:()=>string}){
    if(!validDigest(ledgerIdentityDigest))throw new Error("credential ledger identity invalid");try{hmacSha256Tag(options.integrityKey,{purpose:"credential-ledger-key"});this.#checkpointRead=options.checkpointStore.read.bind(options.checkpointStore);this.#checkpointInitialize=options.checkpointStore.initialize.bind(options.checkpointStore);this.#checkpointAdvance=options.checkpointStore.advance.bind(options.checkpointStore);}catch{throw new Error("credential ledger integrity key invalid");}this.#key=new Uint8Array(options.integrityKey);
    if(path===":memory:"){if(!options.testOnlyAllowEphemeral||options.mode!=="create")throw new Error("credential ledger requires a private file");}else preparePath(path,options.mode);if(options.clock&&!options.testOnlyAllowEphemeral)throw new Error("credential ledger clock injection is test-only");
    this.#db=new DatabaseSync(path);const version=(this.#db.prepare("PRAGMA user_version").get() as{user_version:number}).user_version;
    if((options.mode==="create"&&version!==0)||(options.mode==="open"&&version!==2)){this.#db.close();throw new Error("credential ledger schema invalid");}
    this.#db.exec("PRAGMA journal_mode=DELETE; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");if(options.mode==="create")this.#db.exec(`${tableSql};${metadataSql};`);
    try{assertPrivateSqliteSchemaV1(this.#db,["table:secret_invocation_metadata","table:secret_invocation_records"],{
      secret_invocation_records:[{name:"invocation_id",type:"TEXT",notnull:0,pk:1},{name:"grant_digest",type:"TEXT",notnull:1,pk:0},{name:"grant_json",type:"TEXT",notnull:1,pk:0},{name:"state",type:"TEXT",notnull:1,pk:0},{name:"receipt_json",type:"TEXT",notnull:0,pk:0},{name:"updated_at",type:"TEXT",notnull:1,pk:0}],
      secret_invocation_metadata:[{name:"singleton",type:"INTEGER",notnull:0,pk:1},{name:"ledger_identity_digest",type:"TEXT",notnull:1,pk:0},{name:"revision",type:"INTEGER",notnull:1,pk:0},{name:"high_water_at",type:"TEXT",notnull:1,pk:0},{name:"state_auth_tag",type:"TEXT",notnull:1,pk:0}],
    },{secret_invocation_records:tableSql,secret_invocation_metadata:metadataSql});}catch{this.#db.close();throw new Error("credential ledger schema invalid");}
    let metadata=this.metadata();
    if(options.mode==="create"){const count=this.rows().length;if(metadata||count!==0){this.#db.close();throw new Error("credential ledger state invalid");}const revision=1;this.#db.prepare("INSERT INTO secret_invocation_metadata(singleton,ledger_identity_digest,revision,high_water_at,state_auth_tag) VALUES(1,?,?,?,?)").run(ledgerIdentityDigest,revision,initialHighWater,this.stateTag(revision,initialHighWater));this.#db.exec("PRAGMA user_version=2");metadata=this.metadata();try{this.#checkpointInitialize(this.checkpoint(metadata!));}catch{this.#db.close();this.#key.fill(0);throw new Error("credential ledger checkpoint conflict");}}
    else if(!metadata||metadata.ledger_identity_digest!==ledgerIdentityDigest){this.#db.close();throw new Error("credential ledger identity invalid");}
    try{this.transaction(()=>{for(const row of this.rows())this.verifyRow(row);const now=(options.clock??(()=>new Date().toISOString()))();if(!Number.isFinite(Date.parse(now)))throw new Error("credential ledger clock invalid");const observedAt=new Date(Math.max(Date.parse(now),Date.parse(this.highWater()))).toISOString();this.observe(observedAt);for(const row of this.rows().filter((value)=>value.state==="claimed")){const grant=parseSecretInvocationGrantV1(JSON.parse(row.grant_json)),recordedAt=new Date(Math.max(Date.parse(observedAt),Date.parse(row.updated_at))).toISOString();const receipt=this.recoveryReceipt(grant,recordedAt);this.#db.prepare("UPDATE secret_invocation_records SET state='ambiguous',receipt_json=?,updated_at=? WHERE invocation_id=? AND state='claimed'").run(JSON.stringify(receipt),recordedAt,row.invocation_id);}});}catch(error){this.#db.close();this.#key.fill(0);throw error;}
  }
  close(){this.#db.close();this.#key.fill(0);}
  authorize(grant:SecretInvocationGrantV1){return this.transaction(()=>{const parsed=parseSecretInvocationGrantV1(grant);const row=this.get(parsed.invocationId);if(row){this.verifyRow(row);if(row.grant_digest!==parsed.grantDigest)throw new Error("invocation authorization conflict");return parsed;}this.#db.prepare("INSERT INTO secret_invocation_records(invocation_id,grant_digest,grant_json,state,updated_at) VALUES(?,?,?,'authorized',?)").run(parsed.invocationId,parsed.grantDigest,JSON.stringify(parsed),parsed.issuedAt);return parsed;});}
  terminalReceipt(grant:SecretInvocationGrantV1){return this.transaction(()=>{const parsed=parseSecretInvocationGrantV1(grant),row=this.get(parsed.invocationId);if(!row||row.grant_digest!==parsed.grantDigest)return undefined;this.verifyRow(row);return row.state==="authorized"||row.state==="claimed"?undefined:this.requireReceipt(row);});}
  claim(grant:SecretInvocationGrantV1,claimedAt:string):SecretInvocationClaimV1{return this.transaction(()=>{const parsed=parseSecretInvocationGrantV1(grant);if(!Number.isFinite(Date.parse(claimedAt))||Date.parse(claimedAt)<Date.parse(parsed.issuedAt)||Date.parse(claimedAt)>=Date.parse(parsed.expiresAt))throw new Error("invocation claim time invalid");const row=this.get(parsed.invocationId);if(!row||row.grant_digest!==parsed.grantDigest)throw new Error("invocation not authorized by local broker");this.verifyRow(row);if(row.state==="claimed")return{disposition:"in_progress"};if(row.state!=="authorized")return{disposition:"terminal",receipt:this.requireReceipt(row)};this.observe(claimedAt);this.#db.prepare("UPDATE secret_invocation_records SET state='claimed',updated_at=? WHERE invocation_id=? AND state='authorized'").run(claimedAt,parsed.invocationId);return{disposition:"dispatch"};});}
  settle(grant:SecretInvocationGrantV1,receipt:SecretInvocationReceiptV1){return this.transaction(()=>{const parsed=parseSecretInvocationGrantV1(grant),safeReceipt=secretInvocationReceiptSchemaV1.parse(receipt) as SecretInvocationReceiptV1;assertNoSecretMaterial(safeReceipt,"credential receipt");const row=this.get(parsed.invocationId);if(!row||row.grant_digest!==parsed.grantDigest)throw new Error("invocation settlement conflict");this.verifyRow(row);if(row.state!=="claimed"){const known=this.requireReceipt(row);if(JSON.stringify(known)!==JSON.stringify(safeReceipt))throw new Error("invocation settlement conflict");return known;}if(safeReceipt.invocationId!==parsed.invocationId||safeReceipt.credentialRef!==parsed.credentialRef||Date.parse(safeReceipt.recordedAt)<Date.parse(row.updated_at))throw new Error("invocation settlement conflict");this.observe(safeReceipt.recordedAt);this.#db.prepare("UPDATE secret_invocation_records SET state=?,receipt_json=?,updated_at=? WHERE invocation_id=? AND state='claimed'").run(safeReceipt.state,JSON.stringify(safeReceipt),safeReceipt.recordedAt,parsed.invocationId);return safeReceipt;});}
  receipts(){this.assertState();return this.rows().flatMap((row)=>{this.verifyRow(row);return row.receipt_json?[this.requireReceipt(row)]:[];});}
  private recoveryReceipt(grant:SecretInvocationGrantV1,recordedAt:string){return secretInvocationReceiptSchemaV1.parse({contractVersion:SECRET_BROKER_CONTRACT_V1,invocationId:grant.invocationId,credentialRef:grant.credentialRef,state:"ambiguous",safeCode:"broker_restarted_outcome_unknown",recordedAt,grantsApproval:false,grantsExecutionAuthority:false}) as SecretInvocationReceiptV1;}
  private get(id:string){return this.#db.prepare("SELECT * FROM secret_invocation_records WHERE invocation_id=?").get(id) as Row|undefined;}
  private rows(){return this.#db.prepare("SELECT * FROM secret_invocation_records ORDER BY invocation_id").all() as Row[];}
  private requireReceipt(row:Row){if(!row.receipt_json)throw new Error("credential ledger receipt missing");const receipt=secretInvocationReceiptSchemaV1.parse(JSON.parse(row.receipt_json)) as SecretInvocationReceiptV1;if(receipt.invocationId!==row.invocation_id||receipt.state!==row.state)throw new Error("credential ledger receipt invalid");return receipt;}
  private verifyRow(row:Row){const grant=parseSecretInvocationGrantV1(JSON.parse(row.grant_json));if(grant.invocationId!==row.invocation_id||grant.grantDigest!==row.grant_digest||!Number.isFinite(Date.parse(row.updated_at))||(row.state==="authorized"||row.state==="claimed")!==!row.receipt_json)throw new Error("credential ledger row invalid");if(row.receipt_json)this.requireReceipt(row);}
  private metadata(){return this.#db.prepare("SELECT ledger_identity_digest,revision,high_water_at,state_auth_tag FROM secret_invocation_metadata WHERE singleton=1").get() as LedgerMetadataRow|undefined;}
  private highWater(){const row=this.metadata();if(!row||!Number.isFinite(Date.parse(row.high_water_at)))throw new Error("credential ledger clock invalid");return row.high_water_at;}
  private observe(observedAt:string){if(!Number.isFinite(Date.parse(observedAt))||Date.parse(observedAt)<Date.parse(this.highWater()))throw new Error("credential ledger clock rollback");this.#db.prepare("UPDATE secret_invocation_metadata SET high_water_at=? WHERE singleton=1").run(observedAt);}
  private stateMaterial(revision:number,highWaterAt:string){return{ledgerIdentityDigest:this.ledgerIdentityDigest,revision,highWaterAt,records:this.rows()};}
  private stateTag(revision:number,highWaterAt:string){return hmacSha256Tag(this.#key,this.stateMaterial(revision,highWaterAt));}
  private checkpoint(row:LedgerMetadataRow):RollbackCheckpointV1{const records=this.rows();return{schema:ROLLBACK_CHECKPOINT_SCHEMA_V1,scope:`secret-ledger:${this.ledgerIdentityDigest}`,revision:Number(row.revision),recordCount:records.length,stateDigest:sha256Digest(this.stateMaterial(Number(row.revision),row.high_water_at)),stateAuthTag:row.state_auth_tag};}
  private assertTag(){const row=this.metadata();if(!row||row.ledger_identity_digest!==this.ledgerIdentityDigest||!Number.isSafeInteger(Number(row.revision))||Number(row.revision)<1||!Number.isFinite(Date.parse(row.high_water_at))||!equal(row.state_auth_tag,this.stateTag(Number(row.revision),row.high_water_at)))throw new Error("credential ledger integrity failed");return row;}
  private assertState(){const row=this.assertTag(),expected=this.checkpoint(row);let known:RollbackCheckpointV1|undefined;try{known=this.#checkpointRead(expected.scope);}catch{throw new Error("credential ledger checkpoint unavailable");}if(!known||rollbackCheckpointDigestV1(known)!==rollbackCheckpointDigestV1(expected))throw new Error("credential ledger rollback detected");return expected;}
  private refreshTag(){const current=this.metadata();if(!current)throw new Error("credential ledger integrity failed");const revision=Number(current.revision)+1,tag=this.stateTag(revision,current.high_water_at);this.#db.prepare("UPDATE secret_invocation_metadata SET revision=?,state_auth_tag=? WHERE singleton=1 AND revision=?").run(revision,tag,Number(current.revision));const next=this.metadata();if(!next||Number(next.revision)!==revision)throw new Error("credential ledger integrity failed");return this.checkpoint(next);}
  private transaction<T>(fn:()=>T){this.#db.exec("BEGIN IMMEDIATE");try{const prior=this.assertState();const result=fn();const next=this.refreshTag();try{this.#checkpointAdvance(rollbackCheckpointDigestV1(prior),next);}catch{throw new Error("credential ledger checkpoint conflict");}this.#db.exec("COMMIT");return result;}catch(error){this.#db.exec("ROLLBACK");throw error;}}
}
